### ISSUE TITLE
RuntimeError: Not compiled with GPU support

### ISSUE THREAD

**Issue by yaowangyekong** [xingyizhou/CenterNet#1005]
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/home/zzt/projects/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/zzt/projects/CenterNet/src/lib/detectors/ctdet.py", line 30, in process
    output = self.model(images)[-1]
  File "/home/zzt/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 472, in forward
    x = self.dla_up(x)
  File "/home/zzt/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 411, in forward
    ida(layers, len(layers) -i - 2, len(layers))
  File "/home/zzt/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 384, in forward
    layers[i] = upsample(project(layers[i]))
  File "/home/zzt/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 355, in forward
    x = self.conv(x)
  File "/home/zzt/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 170, in forward
    self.deformable_groups,
  File "/home/zzt/projects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 37, in forward
    ctx.deformable_groups,
RuntimeError: Not compiled with GPU support

How to deal with the problem, could you give me some advice?

**Comment by Dipankar1997161** [comment]
Did you install the DCNv2 as mentioned in the install.md??
