### ISSUE TITLE
no kernel image is available for execution on the device at 

### ISSUE THREAD

**Issue by MIYU8305** [xingyizhou/CenterNet#1009]
I did 
python3 src/demo.py ctdet --demo images --load_model models/ctdet_coco_dla_2x.pth and
python3 src/demo.py multi_pose --demo images --load_model models/multi_pose_dla_3x.pth
Using centernet docker image

I got error
THCudaCheck FAIL file=/pytorch/aten/src/THCUNN/generic/Threshold.cu line=34 error=48 : no kernel image is available for execution on the device
Traceback (most recent call last):
  File "src/demo.py", line 57, in <module>
    demo(opt)
  File "src/demo.py", line 50, in demo
    ret = detector.run(image_name)
  File "/home/user/workdir/src/lib/detectors/base_detector.py", line 118, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/user/workdir/src/lib/detectors/ctdet.py", line 30, in process
    output = self.model(images)[-1]
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/workdir/src/lib/models/networks/pose_dla_dcn.py", line 473, in forward
    x = self.base(x)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/user/workdir/src/lib/models/networks/pose_dla_dcn.py", line 288, in forward
    x = self.base_layer(x)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/modules/activation.py", line 46, in forward
    return F.threshold(input, self.threshold, self.value, self.inplace)
  File "/root/.pyenv/versions/3.6.9/lib/python3.6/site-packages/torch/nn/functional.py", line 624, in threshold
    return torch._C._nn.threshold_(input, threshold, value)
RuntimeError: cuda runtime error (48) : no kernel image is available for execution on the device at /pytorch/aten/src/THCUNN/generic/Threshold.cu:34

How can I solve this?

**Comment by helloyuning** [comment]
Hello, MIYU8305. 
I think your pytorch version mismatch the cuda version, maybe you can check the version and try it again.
Hope it can help

**Comment by Cutewr** [comment]
Have you solved this problem? I also encountered this problem.
