### ISSUE TITLE
ImportError: Building module external.nms failed: ['TypeError: unorderable types: NoneType() >= str()\n']

### ISSUE THREAD

**Issue by wfchenwf** [xingyizhou/CenterNet#104]
Traceback (most recent call last):
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "D:\Python3.5\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "D:\Python3.5\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Python3.5\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Python3.5\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Python3.5\lib\distutils\command\build_ext.py", line 307, in run
    force=self.force)
  File "D:\Python3.5\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Python3.5\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\Python3.5\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
TypeError: unorderable types: NoneType() >= str()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "D:\pythoncode\CenterNet-master\src\lib\detectors\detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "D:\pythoncode\CenterNet-master\src\lib\detectors\exdet.py", line 21, in <module>
    from external.nms import soft_nms
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "D:\Python3.5\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "D:\Python3.5\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "D:\Python3.5\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Python3.5\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Python3.5\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Python3.5\lib\distutils\command\build_ext.py", line 307, in run
    force=self.force)
  File "D:\Python3.5\lib\distutils\ccompiler.py", line 1031, in new_compiler
    return klass(None, dry_run, force)
  File "D:\Python3.5\lib\distutils\cygwinccompiler.py", line 282, in __init__
    CygwinCCompiler.__init__ (self, verbose, dry_run, force)
  File "D:\Python3.5\lib\distutils\cygwinccompiler.py", line 126, in __init__
    if self.ld_version >= "2.10.90":
ImportError: Building module external.nms failed: ['TypeError: unorderable types: NoneType() >= str()\n']

who can tell me what's the problem?how to solve it?thanks

**Comment by xingyizhou** [comment]
I am not able to help debug on windows machines. Make sure you have everything in the right version.
