### ISSUE TITLE
A bug! if I want to train a object detect network just using the msra resnet18 as your paper metioned, how to remodify the code 

### ISSUE THREAD

**Issue by Ai-is-light** [xingyizhou/CenterNet#105]
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    from models.model import create_model, load_model, save_model
  File "../pytorch_detect/CenterNet_point/src/lib/models/model.py", line 14, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "../pytorch_detect/CenterNet_point/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/pytorch_detect/CenterNet_point/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "..pytorch_detect/CenterNet_point/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
ModuleNotFoundError: No module named 'models.networks.DCNv2._ext'

I

the code of model.py

from .networks.dlav0 import get_pose_net as get_dlav0
from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
from .networks.resnet_dcn import get_pose_net as get_pose_net_dcn
from .networks.large_hourglass import get_large_hourglass_net

_model_factory = {
  'res': get_pose_net, # default Resnet with deconv
  'dlav0': get_dlav0, # default DLAup
  'dla': get_dla_dcn,
  'resdcn': get_pose_net_dcn,
  'hourglass': get_large_hourglass_net,
}

**Comment by Ai-is-light** [comment]
And, I'm confused about your code name like get_pose_xx_xx, what's your meaning to use 'pose' especially? you mean that this code only can be used to pose estimation?

**Comment by xingyizhou** [comment]
The error says you haven't compiled DCNv2. `pose` in the function name is copied from Microsoft's simple baseline human pose estimation paper.
