### ISSUE TITLE
Download "dla34-ba72cf86.pth" fails

### ISSUE THREAD

**Issue by yukkyo** [xingyizhou/CenterNet#120]
I got `OSError: [Errno 113] No route to host` when download `dla34-ba72cf86.pth`.
Does anyone know anything?

```bash
~/CenterNet/src$ python test.py ctdet --exp_id coco_dla_2x --keep_res --resume --flip_test
...
Creating model...
Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /home/fujimoto/.torch/models/dla34-ba72cf86.pth
Traceback (most recent call last):
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/fujimoto/.pyenv/versions/3.6.5/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
...
```

**Comment by yukkyo** [comment]
I did not download ctdet_coco_dla_2x
