### ISSUE TITLE
Can you provide loss curve during training

### ISSUE THREAD

**Issue by jjldr** [xingyizhou/CenterNet#147]
When training 3D object detection on my dataset, the rot_loss is much larger than all other losses, is it normal ?  Below is part of my training loss:
![2019-06-17 19-44-01屏幕截图](https://user-images.githubusercontent.com/33213158/59602058-63cbaf80-9138-11e9-8aac-4c5fa4559002.png)

Please help me, thanks!

**Comment by leiyaohui** [comment]
Hello, see you just wrote a question, I want to ask you if you have encountered such a mistake, thank you very much!  
ModuleNotFoundError: No module named 'external.nms'

**Comment by jjldr** [comment]
> Hello, see you just wrote a question, I want to ask you if you have encountered such a mistake, thank you very much!
> ModuleNotFoundError: No module named 'external.nms'

not happened

**Comment by leiyaohui** [comment]
Okay, thank you all the same.

**Comment by saifu-rahman** [comment]
Same issue for me also.. Below is the trace... Please help ..........
am running the command from conda terminal for live webcam:
>python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth
-------------------------------------------------------------------------

(base) D:\Samples\Deep Learning\CenterNet-master\CenterNet\src>python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "D:\Samples\Deep Learning\CenterNet-master\CenterNet\src\lib\detectors\detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "D:\Samples\Deep Learning\CenterNet-master\CenterNet\src\lib\detectors\exdet.py", line 15, in <module>
    from external.nms import soft_nms
ModuleNotFoundError: No module named 'external.nms'

---------------------------------------------------------------------------

**Comment by duytue** [comment]
> Same issue for me also.. Below is the trace... Please help ..........
> am running the command from conda terminal for live webcam:
> 
> > python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth
> 
> (base) D:\Samples\Deep Learning\CenterNet-master\CenterNet\src>python demo.py ctdet --demo webcam --load_model ../models/ctdet_coco_dla_2x.pth
> Traceback (most recent call last):
> File "demo.py", line 11, in 
> from detectors.detector_factory import detector_factory
> File "D:\Samples\Deep Learning\CenterNet-master\CenterNet\src\lib\detectors\detector_factory.py", line 5, in 
> from .exdet import ExdetDetector
> File "D:\Samples\Deep Learning\CenterNet-master\CenterNet\src\lib\detectors\exdet.py", line 15, in 
> from external.nms import soft_nms
> ModuleNotFoundError: No module named 'external.nms'



> Hello, see you just wrote a question, I want to ask you if you have encountered such a mistake, thank you very much!
> ModuleNotFoundError: No module named 'external.nms'

You need to compile NMS in step 6 in [INSTALL.md](https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md)

It says optional but after i compiled that, everything went well.

**Comment by realwill** [comment]
make first

**Comment by ZiyuBao** [comment]
hahaha why do you guys ask random questions here?

**Comment by wangx1996** [comment]
@jjldr  got the same problem，have you find the reason？

**Comment by machengnan** [comment]
@jjldr @wangx1996  got the same problem，have you find the reason？

**Comment by machengnan** [comment]
@jjldr @wangx1996   see here: https://github.com/xingyizhou/CenterTrack/issues/39
