### ISSUE TITLE
ModuleNotFoundError: No module named 'dcn_v2_func'

### ISSUE THREAD

**Issue by CompliceU** [xingyizhou/CenterNet#158]
I just ran the demo and I got this problem. I don't know where the problem is.
Traceback (most recent call last):
  File "src/demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/detectors/exdet.py", line 22, in <module>
    from .base_detector import BaseDetector
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/njfh/yangle/Detention/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from dcn_v2_func import DCNv2Function
ModuleNotFoundError: No module named 'dcn_v2_func'

**Comment by xingyizhou** [comment]
Please make sure you have compiled DCNv2.

**Comment by hanpier** [comment]
Have you sloved the problem?
