### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by oyrq** [xingyizhou/CenterNet#162]
In ubuntu16.0.4 + 2080(8G) + Driver Version: 418.56 + cuda9.2 + cudnn7.1.4 + pytorch0.4.1

python3 demo.py multi_pose --demo ../images/17790319373_bd19b24cfc_k.jpg --load_model ../models/multi_pose_dla_3x.pth

Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/oyrq/Demo/CenterNet/src/lib/../../exp/multi_pose/default
heads {'hm': 1, 'wh': 2, 'hps': 34, 'reg': 2, 'hm_hp': 17, 'hp_offset': 2}
Creating model...
loaded ../models/multi_pose_dla_3x.pth, epoch 320
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/home/oyrq/Demo/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/oyrq/Demo/CenterNet/src/lib/detectors/multi_pose.py", line 28, in process
    output = self.model(images)[-1]
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/Demo/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
    z[head] = self.__getattr__(head)(y[-1])
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

python3 demo.py ctdet --demo ../images/17790319373_bd19b24cfc_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth

Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/oyrq/Demo/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/home/oyrq/Demo/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/home/oyrq/Demo/CenterNet/src/lib/detectors/ctdet.py", line 26, in process
    output = self.model(images)[-1]
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/Demo/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
    z[head] = self.__getattr__(head)(y[-1])
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/oyrq/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by xingyizhou** [comment]
I heard this issue several times but I don't have a good solution myself. The issue is from 2080, but I don't have one to reproduce.

**Comment by oyrq** [comment]
> I heard this issue several times but I don't have a good solution myself. The issue is from 2080, but I don't have one to reproduce.

Now I see, thanks.

**Comment by xingyizhou** [comment]
https://github.com/xingyizhou/CenterNet/issues/184 provides a good solution.

**Comment by oyrq** [comment]
> #184 provides a good solution.

Thanks
