### ISSUE TITLE
demo.py error

### ISSUE THREAD

**Issue by cuizhen00** [xingyizhou/CenterNet#203]
>python demo.py ctdet --demo ../CenterNet-1-master/images/17790319373_bd19b24cfc_k.jpg --load_model ../CenterNet-1-master/models/ctdet_coco_dla_2x.pth
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "D:\CenterNet-master\src\lib\detectors\detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "D:\CenterNet-master\src\lib\detectors\exdet.py", line 11, in <module>
    from progress.bar import Bar
ModuleNotFoundError: No module named 'progress'
thank you

**Comment by qh332612340** [comment]
download the progress module
conda install progress

**Comment by xingyizhou** [comment]
Please follow the readme to install the requirements.
