### ISSUE TITLE
Dataloader and model disagree on output height for custom data

### ISSUE THREAD

**Issue by neighthan** [xingyizhou/CenterNet#223]
I've created a custom dataset which has input images of size 210 x 160. I was using the following command to train on this data:

```bash
python main.py ctdet --exp_id rr_r18 --batch_size 16 --lr 0.625e-4 --dataset my_dataset --arch resdcn_18 --load_model my_model_dir/ctdet_coco_resdcn18.pth
```

But I get an error that the size of `outputs["hm"]` is `16 x 3 x 56 x 40` (3 for 3 classes) while `batch["hm"]` is `16 x 3 x 52 x 40`:

```
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/root/git/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/root/git/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/root/anaconda/envs/symbolic_safe_rl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/git/CenterNet/src/lib/trains/base_trainer.py", line 20, in forward
    loss, loss_stats = self.loss(outputs, batch)
  File "/root/anaconda/envs/symbolic_safe_rl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/git/CenterNet/src/lib/trains/ctdet.py", line 49, in forward
    hm_loss += self.crit(output['hm'], batch['hm']) / opt.num_stacks
  File "/root/anaconda/envs/symbolic_safe_rl/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/git/CenterNet/src/lib/models/losses.py", line 121, in forward
    return self.neg_loss(out, target)
  File "/root/git/CenterNet/src/lib/models/losses.py", line 56, in _neg_loss
    pos_loss = torch.log(pred) * torch.pow(1 - pred, 2) * pos_inds
RuntimeError: The size of tensor a (56) must match the size of tensor b (52) at non-singleton dimension 2
```

Looking at the code for the [detection dataset], we see that `hm`'s height is `input_h // self.opt.down_ratio` where `input_h` is 210 for my images, and I have the default `down_ratio` of 4, yielding a height of 52. Thus the loaded data seems to be the correct shape, but the model outputs are too large. Any idea what could be happening here? Is there some other step for doing custom data that I may have missed? All I did was create a `Dataset` class and include it in `dataset_factory`.

For now, using `--keep_res` has solved the issue for me.

[detection dataset]: https://github.com/xingyizhou/CenterNet/blob/master/src/lib/datasets/sample/ctdet.py

**Comment by xingyizhou** [comment]
Hi, the input resolution needs to be dividable by 32 for dla and resnets (and 128 for hourglass). You will need to change 210 x 160 to 224 x 160.
