### ISSUE TITLE
pytorch0.41+cuda9.0+cudnn7.3+win10，failed complied DCNv2 

### ISSUE THREAD

**Issue by mk123qwe** [xingyizhou/CenterNet#25]
pytorch0.41+cuda9.0+cudnn7.3+win10，failed complied DCNv2 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_double.py", line 43, in <module>
    ffi.build()
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\torch\utils\ffi\__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\torch\utils\ffi\__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\cffi\api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\cffi\recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\cffi\ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "D:\Anaconda3\envs\CenterNet\lib\site-packages\cffi\ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'D:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120

c:\program files\nvidia gpu computing toolkit\cuda\v9.0\include\crt\math_functions.h: warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss

**Comment by xingyizhou** [comment]
I haven't tried windows. Can you check [this](https://github.com/xingyizhou/CenterNet/issues/7)?
