### ISSUE TITLE
【BUG】 while training with --resume

### ISSUE THREAD

**Issue by Qidian213** [xingyizhou/CenterNet#259]
if I use cmd 
`python main.py multi_pose --exp_id dla_3x --dataset coco_hp --batch_size 6 --master_batch 6 --lr 5e-4 --load_model ../models/ctdet_coco_dla_2x.pth --gpus 0 --num_workers 2 --num_epochs 40 --lr_step 20,35`

or 
`python main.py multi_pose --exp_id dla_3x --dataset coco_hp --batch_size 6 --master_batch 6 --lr 5e-4  --gpus 0 --num_workers 2 --num_epochs 40 --lr_step 20,35`

it works well.

but if i want to continue training with cmd

`python main.py multi_pose --exp_id dla_3x --dataset coco_hp --batch_size 6 --master_batch 6 --lr 5e-4 --gpus 0 --num_workers 2 --num_epochs 80 --lr_step 20,35 --resume
`

it cant work 

```
Creating model...
loaded /home/zzg/Opensource/CenterNet/src/lib/../../exp/multi_pose/dla_3x/model_last.pth, epoch 40
Resumed optimizer with start lr 5e-06
Setting up data...
==> initializing keypoints val data.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
Loaded val 4098 samples
==> initializing keypoints train data.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
Loaded train 4098 samples
Starting training...
multi_pose/dla_3x/home/zzg/.local/lib/python3.5/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/zzg/Opensource/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/zzg/Opensource/CenterNet/src/lib/trains/base_trainer.py", line 74, in run_epoch
    self.optimizer.step()
  File "/home/zzg/.local/lib/python3.5/site-packages/torch/optim/adam.py", line 106, in step
    p.data.addcdiv_(-step_size, exp_avg, denom)
RuntimeError: The expanded size of the tensor (1) must match the existing size (7) at non-singleton dimension 0

```
Thanks!

**Comment by xingyizhou** [comment]
Thanks for the report. It happens to me occasionally too, but I didn't find the real causal or solution. Will keep you updated if I figure something out.

**Comment by Qidian213** [comment]
Thanks, and i found the RuntimeError can be different .
eg:
 `RuntimeError: The expanded size of the tensor (14) must match the existing size (2) at non-singleton dimension 0`

`RuntimeError: The expanded size of the tensor (7) must match the existing size (2) at non-singleton dimension 0
`
`RuntimeError: The expanded size of the tensor (2) must match the existing size (7) at non-singleton dimension 0
`

and so on .

What  should be noted that the datasets i use has 7 keypoints for per person  .It can works well , only when i want to  training with --resume encountered this error.

**Comment by xingyizhou** [comment]
Thanks for the additional information. I can see the problem is in loading the optimizer parameters. But not sure how it comes.

**Comment by EzrealLcy** [comment]
Has anyone solved this problem？Thx

**Comment by qiansgithub** [comment]
Has anyone solved this problem？

**Comment by HuangDihe** [comment]
Has anyone solved this problem？Thanks

**Comment by ZiyuBao** [comment]
Is there any update?

**Comment by sihuo521** [comment]
cpoy the 35 line of src/main.py:
 **optimizer = torch.optim.Adam(model.parameters(), opt.lr)** 
paste to 38 line

it will set the optimizer again.
I have tried,it works.
