### ISSUE TITLE
Error while training a new dataset

### ISSUE THREAD

**Issue by BacheryChan** [xingyizhou/CenterNet#285]
Hi
I tried to train the 3D detection task on a new dataset, and met the Error: 
`RuntimeError: The expanded size of the tensor (68) must match the existing size (67) at non-singleton dimension 2`

The whole message as:
```
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/newhome/chenbin/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/newhome/chenbin/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 123, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 133, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/trains/base_trainer.py", line 19, in forward
    outputs = self.model(batch['input'])
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 471, in forward
    x = self.base(x)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 290, in forward
    x = getattr(self, 'level{}'.format(i))(x)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 214, in forward
    x1 = self.tree1(x, residual)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 214, in forward
    x1 = self.tree1(x, residual)
  File "/data/haojing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/newhome/chenbin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 56, in forward
    out += residual
RuntimeError: The expanded size of the tensor (68) must match the existing size (67) at non-singleton dimension 2
```

Does anyone have an idea why it happens and how to fix it?

**Comment by BacheryChan** [comment]
The resolution of the input image is 540 * 960
is it because 540 cannot be divided by 32?
if so, how can I solve it? do I have to resize all the images?

**Comment by xingyizhou** [comment]
You can directly change input_res to `544 x 960`. It will pad with zeros.
