### ISSUE TITLE
ModuleNotFoundError: No module named 'external.nms'

### ISSUE THREAD

**Issue by ssshcj** [xingyizhou/CenterNet#298]
I had a error:
Traceback (most recent call last):
  File "/home/CenterNet/src/demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/CenterNet/src/lib/detectors/exdet.py", line 15, in <module>
    from external.nms import soft_nms
ModuleNotFoundError: No module named 'external.nms'

Can someone help me? Thanks.

**Comment by evitself** [comment]
@ssshcj 
Try `make` under folder `external`, nms module is written in cython pyx, should be built before using it.
