### ISSUE TITLE
检测训练时设置多卡会崩溃，单卡正常

### ISSUE THREAD

**Issue by yanmeizhao** [xingyizhou/CenterNet#324]
多卡崩溃日志：
Done (t=18.70s)
creating index...
index created!
Loaded train 118287 samples
Starting training...
ctdet/coco_dla_2xTraceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/data_parallel.py", line 67, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids, self.chunk_sizes)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/data_parallel.py", line 78, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim, chunk_sizes=self.chunk_sizes)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 30, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim, chunk_sizes) if inputs else []
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 25, in scatter
    return scatter_map(inputs)
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 22, in scatter_map
    return list(map(type(obj), zip(*map(scatter_map, obj.items()))))
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 18, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/zhaoyanmei/projects/CenterNet/src/lib/models/scatter_gather.py", line 15, in scatter_map
    return Scatter.apply(target_gpus, chunk_sizes, dim, obj)
  File "/home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 87, in forward
    outputs = comm.scatter(input, ctx.target_gpus, ctx.chunk_sizes, ctx.dim, streams)
  File "/home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/cuda/comm.py", line 142, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: Chunk size must be positive (scatter at torch/csrc/cuda/comm.cpp:140)
frame #0: <unknown function> + 0xc42a0b (0x7fa1b6a59a0b in /home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
frame #1: <unknown function> + 0x38a5cb (0x7fa1b61a15cb in /home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #12: THPFunction_apply(_object*, _object*) + 0x38f (0x7fa1b657fa2f in /home/work/software/anaconda2/envs/python3.6-pytorch0.4.1/lib/python3.6/site-packages/torch/_C.cpython-36m-x86_64-linux-gnu.so)
能帮忙看下这个问题么

**Comment by xingyizhou** [comment]
I have no ideas. Not sure if using anaconda3 instead of anaconda2 will help.

**Comment by emaniac** [comment]
This happened to me when I trained on 4 GPUs with batch 2. Updating the batch to 4 or any other multiple of GPU number solved the problem.

**Comment by wangminj** [comment]
我也遇到了同样的问题，请问你解决了吗？
