### ISSUE TITLE
你好，换backbone训练出现问题。

### ISSUE THREAD

**Issue by qhykwsw** [xingyizhou/CenterNet#326]
你好，感谢你的贡献，我使用dla和resnet作为backbone在VOC数据集上训练都没有问题。但是我使用自己的bachbone之后，程序输出了以下错误：
ctdet/pascal_swapnet_512Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/minieye/data/hyqian/local/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/minieye/data/hyqian/local/CenterNet/src/lib/trains/base_trainer.py", line 69, in run_epoch
    output, loss, loss_stats = model_with_loss(batch)
  File "/home/minieye/data/hyqian/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/minieye/data/hyqian/local/CenterNet/src/lib/trains/base_trainer.py", line 20, in forward
    loss, loss_stats = self.loss(outputs, batch)
  File "/home/minieye/data/hyqian/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/minieye/data/hyqian/local/CenterNet/src/lib/trains/ctdet.py", line 34, in forward
    output['hm'] = _sigmoid(output['hm'])
TypeError: new(): invalid data type 'str'
我试着输出了一下，output在这里就是一个tensor，不是一个字典，也就没有['hm']的说法。不知是否可以指点一下，如果要添加backbone需要注意些什么么？万分感谢。

**Comment by xingyizhou** [comment]
You will need to make your network output a dict. Please refer to the model files in this repo for reference.
