### ISSUE TITLE
dcn_v2_im2col_cuda_double.cu(248): error: no instance of overloaded function "atomicAdd" matches the argument list argument types are: (double *, double)

### ISSUE THREAD

**Issue by violet17** [xingyizhou/CenterNet#361]
Hi Xingyi, thank you for the great works!
When I ran  make.sh, I met some problems:
```
$ ./make.sh 
dcn_v2_im2col_cuda_double.cu(248): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

1 error detected in the compilation of "/tmp/tmpxft_0000bcd7_00000000-4_dcn_v2_im2col_cuda_double.cpp4.ii".
dcn_v2_psroi_pooling_cuda_double.cu(247): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

dcn_v2_psroi_pooling_cuda_double.cu(248): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

dcn_v2_psroi_pooling_cuda_double.cu(249): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

dcn_v2_psroi_pooling_cuda_double.cu(250): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

dcn_v2_psroi_pooling_cuda_double.cu(265): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

dcn_v2_psroi_pooling_cuda_double.cu(266): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)

6 errors detected in the compilation of "/tmp/tmpxft_0000bd01_00000000-4_dcn_v2_psroi_pooling_cuda_double.cpp4.ii".
/home/crystal/projects/CenterNet/src/lib/models/networks/DCNv2
Traceback (most recent call last):
  File "build.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/crystal/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Traceback (most recent call last):
  File "build_double.py", line 3, in <module>
    from torch.utils.ffi import create_extension
  File "/home/crystal/anaconda3/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

```

The verions of environment are listed below:
python 3.6.7
pytorch 1.0.1.post2
CUDA 9.0  Titan V

**Comment by David-19940718** [comment]
Hello, in the 1.x pytorch version, torch.utils.ffi is deprecated,  you can download from this [url](https://github.com/CharlesShang/DCNv2) and replace it, then you just make again, it may solve.

**Comment by violet17** [comment]
@David-19940718  Thanks1
