### ISSUE TITLE
No such file or directory : ctdet_coco_dla_2x.pth

### ISSUE THREAD

**Issue by haryngod** [xingyizhou/CenterNet#378]
Hi guys. I finally set up and ready to run demo py.
However, I couldn't play it, because follow error.

```
(CenterNet) D:\workspace\CenterNet\src>python demo.py ctdet --demo ../../../1.jpg --load_model ../models/ctdet_coco_dla_2x.pth --debug 2
Fix size testing.
training chunk_sizes: [1]
The output will be saved to  D:\workspace\CenterNet\src\lib\..\..\exp\ctdet\default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 21, in demo
    detector = Detector(opt)
  File "D:\workspace\CenterNet\src\lib\detectors\ctdet.py", line 26, in __init__
    super(CtdetDetector, self).__init__(opt)
  File "D:\workspace\CenterNet\src\lib\detectors\base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "D:\workspace\CenterNet\src\lib\models\model.py", line 34, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\Users\AIW_KHR\Anaconda3\envs\CenterNet\lib\site-packages\torch\serialization.py", line 381, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '../models/ctdet_coco_dla_2x.pth'
```

Do I need to download that file from somewhere? When I check CenterNet\models folder, there is no 
ctdet_coco_dla_2x file. How can I do to solve it?

**Comment by xingyizhou** [comment]
You will need to manually download this model in our model zoo and put it in the directory.

**Comment by haryngod** [comment]
@xingyizhou
Thank you so much. I tried to follow [CenterNet works ok on Pytorch 1.1 + Cuda10.1 + Win10 #7](https://github.com/xingyizhou/CenterNet/issues/7), so it was confused. 

I solved with downloading with your [ZOO](https://drive.google.com/drive/folders/1px-Xg7jXSC79QqgsD1AAGJQkuf5m0zh_) data.
