### ISSUE TITLE
Demo.py Error(Pytorch was complied without Numpy support)

### ISSUE THREAD

**Issue by alfredxing9011** [xingyizhou/CenterNet#407]
Hi, guys. Do have have the same error with me? I tried to run demo.py, but there is an erro I cann't solve it. It seems like this.

Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /opt/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded /opt/CenterNet/models/ctdet_coco_dla_2x.pth, epoch 230
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/opt/CenterNet/src/lib/detectors/base_detector.py", line 105, in run
    images, meta = self.pre_process(image, scale, meta)
  File "/opt/CenterNet/src/lib/detectors/base_detector.py", line 61, in pre_process
    images = torch.from_numpy(images)
RuntimeError: PyTorch was compiled without NumPy support

Can you guys have any ways to solve it? I am sure I'm using Python 3.7, Numpy 1.5.0, Pytorch 0.4.1 and Ubuntu 16.04.
Thank you very much.

**Comment by xingyizhou** [comment]
Can you try to reinstall your pytorch?

**Comment by annyhou** [comment]
Maybe, you can try:
pip uninstall torch
pip install torch==0.4.1.post2
and 
pip uninstall numpy
pip install numpy==1.15.0
