### ISSUE TITLE
run demo error 

### ISSUE THREAD

**Issue by KaaiLee** [xingyizhou/CenterNet#41]
CenterNet work on ubuntu16.04+pytorch0.4.1+python3.5+cuda8.0
I have compile the ./make.sh
when i run the demo.py met error
python demo.py ctdet --demo ../images/ --load_model ../models/ctdet_coco_dla_2x.pth 
error as follows:
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/zkl/Project/Python/rev2019/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'reg': 2, 'wh': 2}
Creating model...
Traceback (most recent call last):
  File "/home/zkl/Project/Python/rev2019/CenterNet/src/demo.py", line 56, in <module>
    demo(opt)
  File "/home/zkl/Project/Python/rev2019/CenterNet/src/demo.py", line 21, in demo
    detector = Detector(opt)
  File "/home/zkl/Project/Python/rev2019/CenterNet/src/lib/detectors/ctdet.py", line 22, in __init__
    super(CtdetDetector, self).__init__(opt)
  File "/home/zkl/Project/Python/rev2019/CenterNet/src/lib/detectors/base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/home/zkl/Project/Python/rev2019/CenterNet/src/lib/models/model.py", line 34, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "/home/zkl/venv/venv_python3.5_pytorch/lib/python3.5/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/zkl/venv/venv_python3.5_pytorch/lib/python3.5/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

Process finished with exit code 1

How can I solve this problem?

**Comment by xingyizhou** [comment]
I guess you haven't completely downloaded the model. Can you re-download the model and try again?

**Comment by KaaiLee** [comment]
ok,i will try again

**Comment by KaaiLee** [comment]
> I guess you haven't completely downloaded the model. Can you re-download the model and try again?

hi,i try again to download the model,but  still occur above problem，eh,Is it because of the python version?Or can you share the model with the Baidu cloud disk?

**Comment by cwjhx** [comment]
when I run the demo.py met error
python demo.py ctdet --demo ../images/ --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /home/e                                                                             c2-user/.torch/models/dla34-ba72cf86.pth
100%|███████████████████████████| 63228658/63228658 [08:19<00:00, 126687.43it/s]
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 21, in demo
    detector = Detector(opt)
  File "/home/CenterNet/src/lib/detectors/ctdet.py", line 22, in __init__
    super(CtdetDetector, self).__init__(opt)
  File "/home/CenterNet/src/lib/detectors/base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "/home//CenterNet/src/lib/models/model.py", line 35, in load_model
    print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
KeyError: 'epoch'

How can I solve this problem?

**Comment by xingyizhou** [comment]
The model works fine in my machine. Please make sure you are using correct python and pytorch version. You can debug by `print(checkpoint.keys())` before `print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))`.

**Comment by cwjhx** [comment]
> The model works fine in my machine. Please make sure you are using correct python and pytorch version. You can debug by `print(checkpoint.keys())` before `print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))`.

 I Commented-Out Code：/base_detector.py      
139 if self.opt.debug >= 1:
140    self.show_results(debugger, image, results)
when I run the demo.py,the model works fine.

**Comment by ClayZhang0403** [comment]
> > I guess you haven't completely downloaded the model. Can you re-download the model and try again?
> 
> hi,i try again to download the model,but still occur above problem，eh,Is it because of the python version?Or can you share the model with the Baidu cloud disk?

hello, have u solve the problem about demo.py error?

**Comment by ClayZhang0403** [comment]
> when I run the demo.py met error
> python demo.py ctdet --demo ../images/ --load_model ../models/ctdet_coco_dla_2x.pth
> Fix size testing.
> training chunk_sizes: [32]
> The output will be saved to /home/CenterNet/src/lib/../../exp/ctdet/default
> heads {'hm': 80, 'wh': 2, 'reg': 2}
> Creating model...
> Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /home/e c2-user/.torch/models/dla34-ba72cf86.pth
> 100%|███████████████████████████| 63228658/63228658 [08:19<00:00, 126687.43it/s]
> Traceback (most recent call last):
> File "demo.py", line 56, in
> demo(opt)
> File "demo.py", line 21, in demo
> detector = Detector(opt)
> File "/home/CenterNet/src/lib/detectors/ctdet.py", line 22, in **init**
> super(CtdetDetector, self).**init**(opt)
> File "/home/CenterNet/src/lib/detectors/base_detector.py", line 25, in **init**
> self.model = load_model(self.model, opt.load_model)
> File "/home//CenterNet/src/lib/models/model.py", line 35, in load_model
> print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
> KeyError: 'epoch'
> 
> How can I solve this problem?
hello, have u solve the problem about demo.py error? i cannot download this dla34-ba72cf86.pth,why i need download this model, i put  the ctdet_coco_dla_2x.pth to the /models

**Comment by cwjhx** [comment]
> > when I run the demo.py met error
> > python demo.py ctdet --demo ../images/ --load_model ../models/ctdet_coco_dla_2x.pth
> > Fix size testing.
> > training chunk_sizes: [32]
> > The output will be saved to /home/CenterNet/src/lib/../../exp/ctdet/default
> > heads {'hm': 80, 'wh': 2, 'reg': 2}
> > Creating model...
> > Downloading: "http://dl.yf.io/dla/models/imagenet/dla34-ba72cf86.pth" to /home/e c2-user/.torch/models/dla34-ba72cf86.pth
> > 100%|███████████████████████████| 63228658/63228658 [08:19<00:00, 126687.43it/s]
> > Traceback (most recent call last):
> > File "demo.py", line 56, in
> > demo(opt)
> > File "demo.py", line 21, in demo
> > detector = Detector(opt)
> > File "/home/CenterNet/src/lib/detectors/ctdet.py", line 22, in **init**
> > super(CtdetDetector, self).**init**(opt)
> > File "/home/CenterNet/src/lib/detectors/base_detector.py", line 25, in **init**
> > self.model = load_model(self.model, opt.load_model)
> > File "/home//CenterNet/src/lib/models/model.py", line 35, in load_model
> > print('loaded {}, epoch {}'.format(model_path, checkpoint['epoch']))
> > KeyError: 'epoch'
> > How can I solve this problem?
> > hello, have u solve the problem about demo.py error? i cannot download this dla34-ba72cf86.pth,why i need download this model, i put  the ctdet_coco_dla_2x.pth to the /models



I have solved the problem,
I Commented-Out Code：/base_detector.py
139 if self.opt.debug >= 1:
140 self.show_results(debugger, image, results)
when I run the demo.py,the model works fine.

**Comment by yds5817** [comment]
@cwjhx  `
Creating model...
Setting up data...
==> initializing coco 2017 val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 100 samples
==> initializing coco 2017 train data.
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loaded train 821 samples
Starting training...
ctdet/coco_dla_1xTraceback (most recent call last):
  File "main.py", line 104, in <module>
    main(opt)
  File "main.py", line 72, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/data/shareJ/YDS/CenterNet-master/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/data/shareJ/YDS/CenterNet-master/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/data/shareJ/YDS/CenterNet-master/src/lib/datasets/sample/ctdet.py", line 103, in __getitem__\n    cls_id = int(self.cat_ids[ann[\'category_id\']])\nKeyError: 0\n`
I tried to comment out the code base_detector. Py
'139 if self.opt.debug> = 1：
140 self.show_results（debugger，image，results）'
But still reported the above error。

**Comment by clemente620** [comment]
> @cwjhx ` Creating model... Setting up data... ==> initializing coco 2017 val data. loading annotations into memory... Done (t=0.00s) creating index... index created! Loaded val 100 samples ==> initializing coco 2017 train data. loading annotations into memory... Done (t=0.01s) creating index... index created! Loaded train 821 samples Starting training... ctdet/coco_dla_1xTraceback (most recent call last): File "main.py", line 104, in <module> main(opt) File "main.py", line 72, in main log_dict_train, _ = trainer.train(epoch, train_loader) File "/data/shareJ/YDS/CenterNet-master/src/lib/trains/base_trainer.py", line 119, in train return self.run_epoch('train', epoch, data_loader) File "/data/shareJ/YDS/CenterNet-master/src/lib/trains/base_trainer.py", line 61, in run_epoch for iter_id, batch in enumerate(data_loader): File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__ return self._process_next_batch(batch) File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch raise batch.exc_type(batch.exc_msg) KeyError: 'Traceback (most recent call last):\n File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/data/shareJ/jhw/python/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/data/shareJ/YDS/CenterNet-master/src/lib/datasets/sample/ctdet.py", line 103, in __getitem__\n cls_id = int(self.cat_ids[ann[\'category_id\']])\nKeyError: 0\n`
> I tried to comment out the code base_detector. Py
> '139 if self.opt.debug> = 1：
> 140 self.show_results（debugger，image，results）'
> But still reported the above error。

are you solve the problem? i met the same issue

**Comment by NipunDewthilina** [comment]
Have you solved this issue?
