### ISSUE TITLE
convert to libtorch

### ISSUE THREAD

**Issue by Wenboisstrong** [xingyizhou/CenterNet#414]

**Comment by Wenboisstrong** [comment]
Here is the specific error message.

Traceback (most recent call last):
  File "/home/kanbig/git/src/pth_to_cplus.py", line 581, in <module>
    traced_script_module = torch.jit.script(model)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1162, in script
    return _convert_to_script_module(obj)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1812, in _convert_to_script_module
    return WeakScriptModuleProxy(mod, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1736, in __init__
    _create_methods_from_stubs(self, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1347, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 982, in _make_strong_submodule
    new_strong_submodule = _convert_to_script_module(module)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1812, in _convert_to_script_module
    return WeakScriptModuleProxy(mod, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1736, in __init__
    _create_methods_from_stubs(self, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1347, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 982, in _make_strong_submodule
    new_strong_submodule = _convert_to_script_module(module)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1812, in _convert_to_script_module
    return WeakScriptModuleProxy(mod, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1386, in init_then_register
    original_init(self, *args, **kwargs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1736, in __init__
    _create_methods_from_stubs(self, stubs)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1347, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/__init__.py", line 1058, in _compile_and_register_class
    ast = get_jit_class_def(obj, obj.__name__)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 143, in get_jit_class_def
    self_name=self_name) for method in methods]
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 143, in <listcomp>
    self_name=self_name) for method in methods]
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 166, in get_jit_def
    return build_def(ctx, py_ast.body[0], type_line, self_name)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 195, in build_def
    param_list = build_param_list(ctx, py_def.args, self_name)
  File "/home/kanbig/Downloads/yes/envs/torch/lib/python3.6/site-packages/torch/jit/frontend.py", line 215, in build_param_list
    raise ValueError(_vararg_kwarg_err)
ValueError: Compiled functions can't take variable number of arguments or use keyword-only arguments with defaults

**Comment by foreversky0611** [comment]
Hi, Wenboisstrong:
Could you share current your covert code for me?
I also want to study libtorch way to transfer model.
Thanks a lot.

**Comment by Wenboisstrong** [comment]
@foreversky0611 
I didn't finish it. I converted the model by trace and registered dcnv2 forward with torchscript. However, my model output changed when I used it. I checked the pre- and post-processing and found that the result of each operation is different when load pt. In my opinion this is very strange . The .pt file should be serialized and the file should not change. I am using this blogger's public project https://github.com/xi11xi19/CenterNet2TorchScript
Https://blog.csdn.net/weixin_45415546/article/details/98728061 This is his blog. You can try it. If it succeeds, please let me know. Thank you.

**Comment by foreversky0611** [comment]
@Wenboisstrong 
Thanks for your message.
I used that sample code and tried to convert dla34 model to pt file, but it will output below abnormal message:
D:\ML\C\CenterNet2TorchScript-master\DCNv2\dcn_v2.py:93: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
self.deformable_groups)
Have you ever encountered this problem?
Thanks a lot.

**Comment by VishnuPJ** [comment]
@Wenboisstrong  Have you managed to solve the issue? I am also getting the same error. I have managed to generate the pt file though. But when i tried to load it using libtorch, its crashing.

**Comment by Wenboisstrong** [comment]
I ended up not using convolution with DCNV2. I use dlav0's network, I have the same problem as  
@foreversky0611  and I think it is this problem that caused my pt model conversion to be unsuccessful. After that and simply modified the above converted code to use dlav0 and track that the conversion was successful and has been successfully verified in C ++.

**Comment by VishnuPJ** [comment]
@Wenboisstrong Yeah i gave up dla_34 and tried hourglass network.Now i was able to generate pt file. Do you have the pre processing and post processing c++ code.Can you share it if you can?
