### ISSUE TITLE
About the reval.py

### ISSUE THREAD

**Issue by DangerousY** [xingyizhou/CenterNet#421]
python reval.py ../../exp/ctdet/oiltank_dla/results.json
Evaluating detections
Traceback (most recent call last):
  File "reval.py", line 78, in <module>
    from_dets(imdb_name, args.detection_file, args)
  File "reval.py", line 71, in from_dets
    imdb.evaluate_detections(nms_dets)
  File "voc_eval_lib/datasets/pascal_voc.py", line 286, in evaluate_detections
    self._write_voc_results_file(all_boxes)
  File "voc_eval_lib/datasets/pascal_voc.py", line 210, in _write_voc_results_file
    with open(filename, 'wt') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/CenterNet/data/voc/VOCdevkit/results/VOC2007/Main/comp4_a559b6b3-34d4-4f25-ac91-42477231b785_det_test_aeroplane.txt'

**I want to ask how can i get the txt file, when i test the code, it only give me a results.json**

**Comment by xingyizhou** [comment]
Please make sure the folder `/home/CenterNet/data/voc/VOCdevkit/results/VOC2007/Main/` exists in your machine. The txt files are generated automatically by the evaluation code.

**Comment by DangerousY** [comment]
> Please make sure the folder `/home/CenterNet/data/voc/VOCdevkit/results/VOC2007/Main/` exists in your machine. The txt files are generated automatically by the evaluation code.

how can i get the results, there is only a results.json and it exits in the exp/ctdet/voc/results.json; Does that mean we can only use the COCO format to get the AP

**Comment by xingyizhou** [comment]
You can use pascal format. Please refer to `pascal.py` for details.

**Comment by zjp99** [comment]
请问你解决了吗？我也有这个问题，这个文件是如何生成的？

**Comment by laisimiao** [comment]
hi,xingyi. what's your meaning of "The VOCdevkit folder is needed to run the evaluation script from faster rcnn." in DATA.md, is the VOCdevkit folder generated when tar VOC dataset?
