### ISSUE TITLE
dcn_v2/_dcn_v2.so: undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by zjp99** [xingyizhou/CenterNet#427]
when i test with ctdet_coco_dla_2x.pth.
-----------------------------------------------------
python /home/zjp/PycharmProjects/CenterNet/src/demo.py ctdet --demo /home/zjp/PycharmProjects/CenterNet/images --load_model /home/zjp/PycharmProjects/CenterNet/models/ctdet_coco_dla_2x.pth
---------------------------------------------------------
Traceback (most recent call last):
  File "/home/zjp/PycharmProjects/CenterNet/src/demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
  File "/home/zjp/PycharmProjects/CenterNet/src/lib/models/networks/DCNv2/_ext/dcn_v2/__init__.py", line 3, in <module>
    from ._dcn_v2 import lib as _lib, ffi as _ffi
ImportError: /home/zjp/PycharmProjects/CenterNet/src/lib/models/networks/DCNv2/_ext/dcn_v2/_dcn_v2.so: undefined symbol: __cudaPopCallConfiguration

**Comment by zjp99** [comment]
我的环境cuda 10.0 py36 pytorch0.4 出现问题
于是我克隆了环境，尝试方法解决，首先我更换了pytorch 1.1 和 torchvision0.3
并且更换DCNv2，最终问题解决
具体参考(https://blog.csdn.net/weixin_38705903/article/details/102598339)
的4.2和6

**Comment by jwnirvana** [comment]
> 我的环境cuda 10.0 py36 pytorch0.4 出现问题
> 于是我克隆了环境，尝试方法解决，首先我更换了pytorch 1.1 和 torchvision0.3
> 并且更换DCNv2，最终问题解决
> 具体参考(https://blog.csdn.net/weixin_38705903/article/details/102598339)
> 的4.2和6

你不是说更换了DCNv2吗？可是你写的博客并没有说这个事情啊

**Comment by zjp99** [comment]
> 
> 
> > 我的环境cuda 10.0 py36 pytorch0.4 出现问题
> > 于是我克隆了环境，尝试方法解决，首先我更换了pytorch 1.1 和 torchvision0.3
> > 并且更换DCNv2，最终问题解决
> > 具体参考(https://blog.csdn.net/weixin_38705903/article/details/102598339)
> > 的4.2和6
> 
> 你不是说更换了DCNv2吗？可是你写的博客并没有说这个事情啊

博客不是我的，我只是更换了pytorch 1.1 和 torchvision0.3
并且更换DCNv2，这两个步骤参考的那个博客的方法，前者参考那个博客的4.2，后者参考6，是更换方法参考（重点）

**Comment by z1277724487** [comment]
This is because Pytorch 0.4.1 does not support cuda>=10.0. You can test it by: 
>>print(torch.version.cuda)
and you will get like this:
9.0.X

So, the solution is install another version of cuda 9.0.
