### ISSUE TITLE
怎么得到网络结构？

### ISSUE THREAD

**Issue by wangshankun** [xingyizhou/CenterNet#43]
不是项目本身问题，学习时候遇到问题；不知道大家遇到过没有，我用torch.save保存的模型，用netron打开没有结构化显示。ctdet_coco_dla_1x.pth本身也只有weight，更无法查看结构了，不知道有什么好的方法可以看到网络结构。

**Comment by YU-FAITH** [comment]
Can u speak English？？

**Comment by Sundrops** [comment]
Here is the caffe prototxt of [Centernet_dlav0_34](https://gist.github.com/Sundrops/09d51c4c25e62f68497d5326193fcad1). If you want to get caffe prototxts of Centernet with other backbones, you can convert the pytorch model to caffe model via [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe)

**Comment by wangshankun** [comment]
> Can u speak English？？

how to shown model structure? same to https://github.com/xingyizhou/CenterNet/issues/40

**Comment by wangshankun** [comment]
> Here is the caffe prototxt of [Centernet_dlav0_34](https://gist.github.com/Sundrops/09d51c4c25e62f68497d5326193fcad1). If you want to get caffe prototxts of Centernet with other backbones, you can convert the pytorch model to caffe model via [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe)

Thanks for your effort ！

**Comment by Sundrops** [comment]
It's more convenient for you to study with the caffe prototxt of [Centernet_res_18](https://gist.github.com/Sundrops/0a21e4b5c48ee3f9f3a3cd042c4d0432).

**Comment by Tim5Tang** [comment]
@Sundrops i use the PytorchToCaffe to convert the Centernet but failed, did you have the fallow question
Traceback (most recent call last):
  File "example/resnet_pytorch_2_caffe.py", line 13, in <module>
    resnet18.load_state_dict(checkpoint)
  File "/home/tangzixing/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNet:
        Missing key(s) in state_dict: "conv1.weight", "bn1.weight", "bn1.bias", "bn1.running_mean", "bn1.running_var", "layer1.0.conv1.weight", "layer1.0.bn1.weight", "layer1.0.bn1.bias", "layer1.0.bn1.running_mean", "layer1.0.bn1.running_var", "layer1.0.conv2.weight", "layer1.0.bn2.weight", "layer1.0.bn2.bias", "layer1.0.bn2.running_mean", "layer1.0.bn2.running_var", "layer1.1.conv1.weight", "layer1.1.bn1.weight", "layer1.1.bn1.bias", "layer1.1.bn1.running_mean", "layer1.1.bn1.running_var", "layer1.1.conv2.weight", "layer1.1.bn2.weight", "layer1.1.bn2.bias", "layer1.1.bn2.running_mean", "layer1.1.bn2.running_var", "layer2.0.conv1.weight", "layer2.0.bn1.weight", "layer2.0.bn1.bias", "layer2.0.bn1.running_mean", "layer2.0.bn1.running_var", "layer2.0.conv2.weight", "layer2.0.bn2.weight", "layer2.0.bn2.bias", "layer2.0.bn2.running_mean", "layer2.0.bn2.running_var", "layer2.0.downsample.0.weight", "layer2.0.downsample.1.weight", "layer2.0.downsample.1.bias", "layer2.0.downsample.1.running_mean", "layer2.0.downsample.1.running_var", "layer2.1.conv1.weight", "layer2.1.bn1.weight", "layer2.1.bn1.bias", "layer2.1.bn1.running_mean", "layer2.1.bn1.running_var", "layer2.1.conv2.weight", "layer2.1.bn2.weight", "layer2.1.bn2.bias", "layer2.1.bn2.running_mean", "layer2.1.bn2.running_var", "layer3.0.conv1.weight", "layer3.0.bn1.weight", "layer3.0.bn1.bias", "layer3.0.bn1.running_mean", "layer3.0.bn1.running_var", "layer3.0.conv2.weight", "layer3.0.bn2.weight", "layer3.0.bn2.bias", "layer3.0.bn2.running_mean", "layer3.0.bn2.running_var", "layer3.0.downsample.0.weight", "layer3.0.downsample.1.weight", "layer3.0.downsample.1.bias", "layer3.0.downsample.1.running_mean", "layer3.0.downsample.1.running_var", "layer3.1.conv1.weight", "layer3.1.bn1.weight", "layer3.1.bn1.bias", "layer3.1.bn1.running_mean", "layer3.1.bn1.running_var", "layer3.1.conv2.weight", "layer3.1.bn2.weight", "layer3.1.bn2.bias", "layer3.1.bn2.running_mean", "layer3.1.bn2.running_var", "layer4.0.conv1.weight", "layer4.0.bn1.weight", "layer4.0.bn1.bias", "layer4.0.bn1.running_mean", "layer4.0.bn1.running_var", "layer4.0.conv2.weight", "layer4.0.bn2.weight", "layer4.0.bn2.bias", "layer4.0.bn2.running_mean", "layer4.0.bn2.running_var", "layer4.0.downsample.0.weight", "layer4.0.downsample.1.weight", "layer4.0.downsample.1.bias", "layer4.0.downsample.1.running_mean", "layer4.0.downsample.1.running_var", "layer4.1.conv1.weight", "layer4.1.bn1.weight", "layer4.1.bn1.bias", "layer4.1.bn1.running_mean", "layer4.1.bn1.running_var", "layer4.1.conv2.weight", "layer4.1.bn2.weight", "layer4.1.bn2.bias", "layer4.1.bn2.running_mean", "layer4.1.bn2.running_var", "fc.weight", "fc.bias".
        Unexpected key(s) in state_dict: "epoch", "state_dict".

**Comment by Sundrops** [comment]
No. Maybe you can try resnet18.load_state_dict(checkpoint["state_dict"]).

**Comment by monoloxo** [comment]
git上有一个netron的工具，可以在线查看主流框架的网络结构。

**Comment by XzlXcc** [comment]
> git上有一个netron的工具，可以在线查看主流框架的网络结构。

Have you visualized it through the tool?

**Comment by wangshankun** [comment]
> git上有一个netron的工具，可以在线查看主流框架的网络结构。

最开始就是用netron了
ctdet_coco_dla_1x.pth在torchsummary、tensorboardX、make_dot、Netron都没办法正常显示，最多显示一部分node

**Comment by cwjhx** [comment]
> Here is the caffe prototxt of [Centernet_dlav0_34](https://gist.github.com/Sundrops/09d51c4c25e62f68497d5326193fcad1). If you want to get caffe prototxts of Centernet with other backbones, you can convert the pytorch model to caffe model via [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe)

请问Centernet_dlav0_34 这个模型怎么训练得到？

**Comment by cwjhx** [comment]
> Here is the caffe prototxt of [Centernet_dlav0_34](https://gist.github.com/Sundrops/09d51c4c25e62f68497d5326193fcad1). If you want to get caffe prototxts of Centernet with other backbones, you can convert the pytorch model to caffe model via [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe)

请问：caffe prototxt of Centernet_dlav0_34，具体怎么操作？谢谢

**Comment by djshen** [comment]
I visualized ctdet_coco_dla_2x by directly modifying pytorch and centernet code.

![](https://i.imgur.com/nu7ZSr7.jpg)

**Comment by XzlXcc** [comment]
> I visualized ctdet_coco_dla_2x by directly modifying pytorch and centernet code.
> 
> ![](https://camo.githubusercontent.com/e28738c50e9f28e5247d5986e042981d2e8fad9b/68747470733a2f2f692e696d6775722e636f6d2f6e75375a5372372e6a7067)

Hi, which tool do you use to visualize it?

**Comment by djshen** [comment]
I modified torch/nn/modules/module.py
Specifically, I add some code in Module.__call__ function to trace the inputs and outputs of the modules (store each of the tensors or modules and give it a unique name).
Then I print the connections between inputs and modules in `dot` format, and visualize it by graphviz.

**Comment by 2018newyangyu** [comment]
> I modified `torch/nn/modules/module.py`
> Specifically, I add some code in `Module.__call__` function to trace the inputs and outputs of the modules (store each of the tensors or modules and give it a unique name).
> Then I print the connections between inputs and modules in `dot` format, and visualize it by graphviz.

@djshen  Can you visiualize the hourglass?

**Comment by djshen** [comment]
@2018newyangyu 
https://i.imgur.com/0GVHoDU.png

**Comment by JacobYuan7** [comment]
@djshen sorry to interrupt, but I can't open this link even through a VPN, can you offer a new link?

**Comment by djshen** [comment]
@2018newyangyu
<details>
<summary>Click</summary>

![](https://i.imgur.com/0GVHoDU.png)
</details>

**Comment by lsccccc** [comment]
hi, I convert dlav0_34 based model to caffe model by [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe), then visualize the network structure by [netscope](http://ethereon.github.io/netscope/#/editor).
So why these two BN layers didn't connect with anywhere?
![image](https://user-images.githubusercontent.com/43127532/71050985-b63a6700-2181-11ea-9fab-999ed4997256.png)
![image](https://user-images.githubusercontent.com/43127532/71051002-c3efec80-2181-11ea-8dd5-dd69ea775138.png)

**Comment by monoloxo** [comment]
@lsccccc Sorry can not provide more help, I just used it to view the network map of yolo

**Comment by lsccccc** [comment]
> @lsccccc Sorry can not provide more help, I just used it to view the network map of yolo

thank u any way

**Comment by lsccccc** [comment]
@djshen Hi, could you please visualize the dlav0 based net?

**Comment by zjp99** [comment]
> 
> 
> I modified `torch/nn/modules/module.py`
> Specifically, I add some code in `Module.__call__` function to trace the inputs and outputs of the modules (store each of the tensors or modules and give it a unique name).
> Then I print the connections between inputs and modules in `dot` format, and visualize it by graphviz.

can you show your code?

**Comment by Clemente420** [comment]
> Here is the caffe prototxt of [Centernet_dlav0_34](https://gist.github.com/Sundrops/09d51c4c25e62f68497d5326193fcad1). If you want to get caffe prototxts of Centernet with other backbones, you can convert the pytorch model to caffe model via [PytorchToCaffe](https://github.com/xxradon/PytorchToCaffe)

THANKS FOR YOUR JOB!!! :)

**Comment by Vankeee** [comment]
@djshen  Thanks for sharing the pics! 
I have a question about the nodes. What does P_weight_1 mean?(Sorry, I am newbee)

**Comment by djshen** [comment]
> @djshen Thanks for sharing the pics!
> I have a question about the nodes. What does P_weight_1 mean?(Sorry, I am newbee)

In this graph, the node name starting with "P_" is a parameter and is passed to the corresponding operation such as a convolution.

**Comment by Vankeee** [comment]
@djshen  Thanks.I see that. P_weight_1 is the parameter of the first covolution layer.
