### ISSUE TITLE
Run demo error

### ISSUE THREAD

**Issue by WAN96** [xingyizhou/CenterNet#432]
Hi, when I run the demo.py, I got this:
(CenterNet) wx@wx-computer:~/Downloads/CenterNet-master/src$ python demo.py ctdet --demo ../images/33823288584_1d21cf0a26_k.jpg  --load_model ../models/ctdet_coco_dla_2x.pth --gpu -1
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/wx/Downloads/CenterNet-master/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/wx/Downloads/CenterNet-master/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/home/wx/Downloads/CenterNet-master/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/wx/Downloads/CenterNet-master/src/lib/models/model.py", line 5, in <module>
    import torchvision.models as models
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/models/__init__.py", line 12, in <module>
    from . import detection
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/models/detection/faster_rcnn.py", line 13, in <module>
    from .rpn import AnchorGenerator, RPNHead, RegionProposalNetwork
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/models/detection/rpn.py", line 8, in <module>
    from . import _utils as det_utils
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torchvision/models/detection/_utils.py", line 74, in <module>
    @torch.jit.script
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/__init__.py", line 364, in script
    graph = _script_graph(fn, _frames_up=_frames_up + 1)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/__init__.py", line 359, in _script_graph
    ast = get_jit_ast(fn)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 132, in get_jit_ast
    return build_def(SourceRangeFactory(source), py_ast.body[0])
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 151, in build_def
    build_stmts(ctx, body))
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 123, in build_stmts
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 123, in <listcomp>
    stmts = [build_stmt(ctx, s) for s in stmts]
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 205, in build_Assign
    rhs = build_expr(ctx, stmt.value)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 314, in build_Call
    func = build_expr(ctx, expr.func)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 300, in build_Attribute
    value = build_expr(ctx, expr.value)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 140, in __call__
    return method(ctx, node)
  File "/home/wx/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/jit/frontend.py", line 422, in build_Subscript
    raise NotSupportedError(base.range(), "slicing multiple dimensions at the same time isn't supported yet")
torch.jit.frontend.NotSupportedError: slicing multiple dimensions at the same time isn't supported yet
        proposals (Tensor): boxes to be encoded
    """

    # perform some unpacking to make it JIT-fusion friendly
    wx = weights[0]
    wy = weights[1]
    ww = weights[2]
    wh = weights[3]

    proposals_x1 = proposals[:, 0].unsqueeze(1)
                   ~~~~~~~~~ <--- HERE
    proposals_y1 = proposals[:, 1].unsqueeze(1)
    proposals_x2 = proposals[:, 2].unsqueeze(1)
    proposals_y2 = proposals[:, 3].unsqueeze(1)

    reference_boxes_x1 = reference_boxes[:, 0].unsqueeze(1)
    reference_boxes_y1 = reference_boxes[:, 1].unsqueeze(1)
    reference_boxes_x2 = reference_boxes[:, 2].unsqueeze(1)
    reference_boxes_y2 = reference_boxes[:, 3].unsqueeze(1)

Do you know how to fix it?

**Comment by huang6886** [comment]
I met the same problem, have you solved it ?

**Comment by xingyizhou** [comment]
Can you try to re-install your pytorch?

**Comment by yourlovedu** [comment]
I met the same problem, have anyone  solved it ?
