### ISSUE TITLE
test on voc07

### ISSUE THREAD

**Issue by zjp99** [xingyizhou/CenterNet#441]
Traceback (most recent call last):
  File "tools/reval.py", line 78, in <module>
    from_dets(imdb_name, args.detection_file, args)
  File "tools/reval.py", line 54, in from_dets
    imdb = pascal_voc('test', '2007')
  File "tools/voc_eval_lib/datasets/pascal_voc.py", line 44, in __init__
    self._image_index = self._load_image_set_index()
  File "tools/voc_eval_lib/datasets/pascal_voc.py", line 87, in _load_image_set_index
    'Path does not exist: {}'.format(image_set_file)
AssertionError: Path does not exist: /home/zjp/PycharmProjects/CenterNet/data/voc/VOCdevkit/VOC2007/ImageSets/Main/test.txt
----------------------------------------------------------------------------------------------------
VOCdevkit  how to download?

**Comment by zjp99** [comment]
The VOCdevkit folder is needed to run the evaluation script from faster rcnn.
[https://github.com/rbgirshick/py-faster-rcnn/blob/master/tools/reval.py](url)
what should i do?
