### ISSUE TITLE
python main.py  ERROR cls_id = int(self.cat_ids[ann[\'category_id\']])\nKeyError: 0\n' 

### ISSUE THREAD

**Issue by clemente620** [xingyizhou/CenterNet#486]
Creating model...
Setting up data...
==> initializing seaship val data.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
Loaded val 7000 samples
==> initializing seaship train data.
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
Loaded train 7000 samples
Starting training...
ctdet/seashipTraceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/joe/Desktop/centernet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/joe/Desktop/centernet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/joe/Desktop/centernet/src/lib/datasets/sample/ctdet.py", line 102, in __getitem__\n    cls_id = int(self.cat_ids[ann[\'category_id\']])\nKeyError: 0\n'

**Comment by ngunauj** [comment]
应该是类别id不太对，看看自己的json数据。
It should be that the category id is not right, look at your json data

**Comment by David-19940718** [comment]
@clemente620 
start your id from [0, 1, ...] which corresponding to your modify classes, such as classes = ['__background__', 'class1',  'class2'], then you should set ids = [0, 1, 2]. It may be solved.

**Comment by Tharindi-Liyanage** [comment]
> Creating model... Setting up data... ==> initializing seaship val data. loading annotations into memory... Done (t=0.06s) creating index... index created! Loaded val 7000 samples ==> initializing seaship train data. loading annotations into memory... Done (t=0.03s) creating index... index created! Loaded train 7000 samples Starting training... ctdet/seashipTraceback (most recent call last): File "main.py", line 102, in main(opt) File "main.py", line 70, in main log_dict_train, _ = trainer.train(epoch, train_loader) File "/home/joe/Desktop/centernet/src/lib/trains/base_trainer.py", line 119, in train return self.run_epoch('train', epoch, data_loader) File "/home/joe/Desktop/centernet/src/lib/trains/base_trainer.py", line 61, in run_epoch for iter_id, batch in enumerate(data_loader): File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 637, in **next** return self._process_next_batch(batch) File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch raise batch.exc_type(batch.exc_msg) KeyError: 'Traceback (most recent call last):\n File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/home/joe/miniconda3/envs/centernet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 138, in \n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/home/joe/Desktop/centernet/src/lib/datasets/sample/ctdet.py", line 102, in **getitem**\n cls_id = int(self.cat_ids[ann['category_id']])\nKeyError: 0\n'

Hi! Did you solve this issue?
