### ISSUE TITLE
undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonEv

### ISSUE THREAD

**Issue by TimLiujn** [xingyizhou/CenterNet#49]
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/app/ljn_work/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/app/ljn_work/CenterNet/src/lib/detectors/exdet.py", line 23, in <module>
    from .base_detector import BaseDetector
  File "/app/ljn_work/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/app/ljn_work/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/app/ljn_work/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/app/ljn_work/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /app/ljn_work/CenterNet/src/lib/models/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonEv

**Comment by CompliceU** [comment]
did you solve it ? i meet the same issues with you @TimLiujn

**Comment by HuangDihe** [comment]
i meet the same issues, did you solve it? @TimLiujn @CompliceU
