### ISSUE TITLE
AttributeError: Caught AttributeError in DataLoader worker process 0.

### ISSUE THREAD

**Issue by Sdy344** [xingyizhou/CenterNet#510]
Creating model...
Setting up data...
==> initializing coco 2017 val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 108 samples
==> initializing coco 2017 train data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded train 170 samples
Starting training...
ctdet/coco_dlaTraceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/sdy/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/sdy/CenterNet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sdy/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/sdy/CenterNet/src/lib/datasets/sample/ctdet.py", line 39, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by xingyizhou** [comment]
It is because the image is not loaded. Please check you have placed the dataset correctly.

**Comment by Sdy344** [comment]
Thank you very much for your reply. My problem has been solved. The problem is that I made a mistake when I converted the VOC data format to coco data format




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xingyi Zhou"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月6日(星期五) 上午6:35
收件人:&nbsp;"xingyizhou/CenterNet"<CenterNet@noreply.github.com&gt;;
抄送:&nbsp;"Clear"<344397214@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xingyizhou/CenterNet] AttributeError: Caught AttributeError in DataLoader worker process 0. (#510)




It is because the image is not loaded. Please check you have placed the dataset correctly.

**Comment by nomantanveer-E06** [comment]
I had an empty line in the end of my train.txt file, which caused this error.

**Comment by bibixiuxiuxiu** [comment]
请问怎么检查

**Comment by Sdy344** [comment]
> 请问怎么检查
多从网上找几份转换代码都试试看

**Comment by wangqiang-66** [comment]
想问下这是数据集路径没有放好的原因吗

**Comment by Sdy344** [comment]
> 想问下这是数据集路径没有放好的原因吗
可能是，有可能是数据集缺失

**Comment by Dragon201701** [comment]
I have had this issue recently training the CenterTrack. It turns out that the last frame of the output from FFmpeg is missing. In my case, ffmpeg gives me frame 1 to 1064 while my coco json which is converted from pascal voc xml format has 1 to 1065 so the last image is missing. The error is so confuse that I print out the index and verified the image at that index exists and can be loaded.
