### ISSUE TITLE
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by IaroslavS** [xingyizhou/CenterNet#545]
Hi.
I followed instructions for installation - https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md
I stopped at point 5:

Compile deformable convolutional (from DCNv2).

cd $CenterNet_ROOT/src/lib/external
make

At first i got error that "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead"
Then I ran "conda install pytorch=0.4.1 torchvision -c pytorch"
After that I got these errors:
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda_double.cu.o: No such file or directory
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda_double.cu.
o: No such file or directory

But this file actually exists - see print screen below

![Screenshot at 2019-12-26 17-32-43](https://user-images.githubusercontent.com/47471352/71479561-fa72da80-2805-11ea-94d4-2b40d15a67a0.png)

Full output in console is provided below:

-------------------------------------------------------------------------------------------------------------------------

./make.sh: line 5: nvcc: command not found
./make.sh: line 6: nvcc: command not found
./make.sh: line 9: nvcc: command not found
./make.sh: line 10: nvcc: command not found
/home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2
Including CUDA code.
/home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2
generating /tmp/tmpqk8owl8p/_dcn_v2.c
setting the current directory to '/tmp/tmpqk8owl8p'
running build_ext
building '_dcn_v2' extension
creating home
creating home/solomentsev_yaroslav
creating home/solomentsev_yaroslav/Jupyter_Notebook
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c _dcn_v2.c -o ./_dcn_v2.o -std=c99 -fopenmp -std=c99
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2.c -o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2.o -std=c99 -fopenmp -std=c99
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.c -o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.o -std=c99 -fopenmp -std=c99
gcc -pthread -shared -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -L/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib -Wl,-rpath=/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_dcn_v2.o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2.o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda.o /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu.o /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu.o -o ./_dcn_v2.so
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda.cu.o: No such file or directory
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 43, in <module>
    ffi.build()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/recompiler.py", line 1527, in recompile
    compiler_verbose, debug)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1
Including CUDA code.
/home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2
generating /tmp/tmprj3u5t_c/_dcn_v2_double.c
setting the current directory to '/tmp/tmprj3u5t_c'
running build_ext
building '_dcn_v2_double' extension
creating home
creating home/solomentsev_yaroslav
creating home/solomentsev_yaroslav/Jupyter_Notebook
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2
creating home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c _dcn_v2_double.c -o ./_dcn_v2_double.o -std=c99 -fopenmp -std=c99
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_double.c -o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_double.o -std=c99 -fopenmp -std=c99
gcc -pthread -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/solomentsev_yaroslav/.conda/envs/CenterNet/include/python3.6m -c /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda_double.c -o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda_double.o -std=c99 -fopenmp -std=c99
gcc -pthread -shared -B /home/solomentsev_yaroslav/.conda/envs/CenterNet/compiler_compat -L/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib -Wl,-rpath=/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib -Wl,--no-as-needed -Wl,--sysroot=/ ./_dcn_v2_double.o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_double.o ./home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/dcn_v2_cuda_double.o /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda_double.cu.o /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda_double.cu.o -o ./_dcn_v2_double.so
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_im2col_cuda_double.cu.o: No such file or directory
gcc: error: /home/solomentsev_yaroslav/Jupyter_Notebook/CenterNet/src/lib/models/networks/DCNv2/src/cuda/dcn_v2_psroi_pooling_cuda_double.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build_double.py", line 43, in <module>
    ffi.build()
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/recompiler.py", line 1527, in recompile
    compiler_verbose, debug)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/solomentsev_yaroslav/.conda/envs/CenterNet/lib/python3.6/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'gcc' failed with exit status 1

----------------------------------------------------------------------------------------------------------------------------

**Comment by xingyizhou** [comment]
Can you make sure you pytorch version aligns with the DCNv2 required pytorch version?

**Comment by 4444borja** [comment]
I think your problem is that nvcc is not properly installed on your machine, as you can see by the first lines of the error message:

>./make.sh: line 5: nvcc: command not found
>./make.sh: line 6: nvcc: command not found
>./make.sh: line 9: nvcc: command not found
>./make.sh: line 10: nvcc: command not found

It does not compile the source code, so later it gives an error when trying to find the object files as they have not been generated.

I had the same issue, and to solve it I follow the instructions in this link:
https://askubuntu.com/questions/885610/nvcc-version-command-says-nvcc-is-not-installed

Essentially, you have to add to your PATH and LD_LIBRARY_PATH the CUDA binaries, you do so by adding this two lines to your ~/.bashrc file:

export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}$ 
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

(Change the cuda version depending on the one that you have installed)

Then open a new terminal or execute "source ~/.bashrc" to apply the changes and run the installation script again, it should work.

**Comment by IaroslavS** [comment]
> Can you make sure you pytorch version aligns with the DCNv2 required pytorch version?

Sorry, I didn't get notification on my e-mail about your reply and later I gave up with CenterNet. I think, this issue can be closed.
