### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.debugger'

### ISSUE THREAD

**Issue by Eyren** [xingyizhou/CenterNet#562]
```
python demo.py ctdet --demo /home/CenterNet/images/ --load_model/home/CenterNet/models/ctdet_coco_dla_2x.pth
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/ldsw/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/ldsw/CenterNet/src/lib/detectors/exdet.py", line 19, in <module>
    from utils.debugger import Debugger
ModuleNotFoundError: No module named 'utils.debugger'

```
Thank you.

**Comment by Eyren** [comment]
My mistake!!Ignore me....
