### ISSUE TITLE
undefined symbol: __cudaPopCallConfiguration

### ISSUE THREAD

**Issue by MARMOTatZJU** [xingyizhou/CenterNet#585]
My PC has CUDA 10.0 and pytorch 0.4.1. I created and configured a conda env according to your [instruaction](https://github.com/xingyizhou/CenterNet/blob/master/readme/INSTALL.md). I can compile DCVv2.
However, I can not launch the test due to error "undefined symbol: __cudaPopCallConfiguration". Based on Google result, this may be caused by incompatible Pytorch version and CUDA version.
```
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
  File "/home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/networks/DCNv2/_ext/dcn_v2/__init__.py", line 3, in <module>
    from ._dcn_v2 import lib as _lib, ffi as _ffi
ImportError: /home/lan/Documents/xuyinda/Projects/CenterNet/src/lib/models/networks/DCNv2/_ext/dcn_v2/_dcn_v2.so: undefined symbol: __cudaPopCallConfiguration
```
The commands that I ran is here: 
```
export PYTHONPATH=/home/lan/anaconda3/envs/CenterNet/lib/python3.6/site-packages
cd ./src
python3 test.py multi_pose --exp_id dla --keep_res --load_model ../models/multi_pose_dla_3x.pth --flip_test
```
Awaiting your help over possible solution over this issue. Thanks in advance!

**Comment by MARMOTatZJU** [comment]
More concretely, how can I train a network without DCNv2? 
Because I do not have pressure in terms of COCO AP. I deploy this on my Robotics system so the only need is to build a runnable program instead of persuing high COCO AP.

**Comment by MARMOTatZJU** [comment]
[UPDATE]
Solved by following [this issue](https://github.com/xingyizhou/CenterNet/issues/7)

**Comment by 593903762** [comment]
I want to ask you whether recreate the env(install the pytorch 1.1) or do other things. I have met the same issue as you. Hope for your reply.
