### ISSUE TITLE
CUDA verison problem

### ISSUE THREAD

**Issue by Midhilesh29** [xingyizhou/CenterNet#596]
```
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/workspace/midhilesh/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/workspace/midhilesh/CenterNet/src/lib/detectors/ctdet.py", line 30, in process
    output = self.model(images)[-1]
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/midhilesh/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 471, in forward
    x = self.base(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/midhilesh/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 288, in forward
    x = self.base_layer(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)

```

I got this error while using the demo file. Can anyone please help me with this problem?

I used Pytorch 0.4.1, CUDA 9.0.176

**Comment by xingyizhou** [comment]
It seems a pytorch installation issue. Can you make sure you can run other pytorch projects under this environment?

**Comment by wjgarnett** [comment]
have you sovled this problem???

**Comment by XavierYoungY** [comment]
Has anyone solved this problem?

**Comment by lhyfst** [comment]
I met this problem, too.

**Comment by liushuai839** [comment]
> I met this problem, too.
have you solve this problem??   It  disturb me  for 2days!!!

**Comment by xiaowk5516** [comment]
fobidden cudnn in code

`import torch

torch.backends.cudnn.enabled=False`

**Comment by lhyfst** [comment]
try a different batch size.

**Comment by sh7jacobi** [comment]
I have the same problem. Different batch size did not solve this problem

**Comment by sh7jacobi** [comment]
> fobidden cudnn in code
> 
> `import torch
> 
> torch.backends.cudnn.enabled=False`

It helped me. I added this code to test,py at first

**Comment by GabrielGuez** [comment]
> fobidden cudnn in code
> 
> `import torch
> 
> torch.backends.cudnn.enabled=False`

Should I do that even if the project is supposed to use cudnn ? I don't know if it makes sense...a bit lost ^^

**Comment by sh7jacobi** [comment]
@GabrielGuez, I think you can learn this model by setting torch.backends.cudnn.enabled=False. But I am not sure it will work correctly if you implement the model in another project, where it needs cudnn.

**Comment by GabrielGuez** [comment]
@sh7jacobi Thank you for your answer. After further investigation, it seems that torch.backends.cudnn.benchmark = True did the trick :)
Apparently it 'optimizes' CuDNN somehow, don't really understand how thought. If someone have an idea how it works, don't hesitate to give a quick explanation.
Have a good day.

**Comment by mahmoudEltaher** [comment]
> 
> 
> @sh7jacobi Thank you for your answer. After further investigation, it seems that torch.backends.cudnn.benchmark = True did the trick :)
> Apparently it 'optimizes' CuDNN somehow, don't really understand how thought. If someone have an idea how it works, don't hesitate to give a quick explanation.
> Have a good day.

Thanks that is worked with me :)

**Comment by pinky1812** [comment]
> @sh7jacobi Thank you for your answer. After further investigation, it seems that torch.backends.cudnn.benchmark = True did the trick :)
> Apparently it 'optimizes' CuDNN somehow, don't really understand how thought. If someone have an idea how it works, don't hesitate to give a quick explanation.
> Have a good day.

Worked for me too

**Comment by Nishikanta059** [comment]
> @sh7jacobi Thank you for your answer. After further investigation, it seems that torch.backends.cudnn.benchmark = True did the trick :) Apparently it 'optimizes' CuDNN somehow, don't really understand how thought. If someone have an idea how it works, don't hesitate to give a quick explanation. Have a good day.

its working ,means no errors but its using cpu instead of gpu .Can you suggest how to train it on gpu ?
