### ISSUE TITLE
I have it training in windows with num_workers > 0

### ISSUE THREAD

**Issue by Ceeeeeeeeeeeeeeb** [xingyizhou/CenterNet#600]
I have it training in windows with num_workers > 0

Basically the error boils down to Can't pickle local object 'get_dataset.<locals>.Dataset'

From the python pickle docs: only classes that are defined at the top level of a module are picklable.

The Dataset object is defined dynamically in src\lib\datasets\dataset_factory.py based on the options you pass in from the command line.
```python3
def get_dataset(dataset, task):
  class Dataset(dataset_factory[dataset], _sample_factory[task]):
    pass
  return Dataset
```
What you will notice is that this class is defined in a function and not in the top level! So to fix this I made a small workaround:
```python3
class MyDataset(dataset_factory['mydataset'], _sample_factory['ctdet']):
  pass

def get_dataset(dataset, task):
  if dataset == 'mydataset' and task == 'ctdet':
    return MyDataset
  class Dataset(dataset_factory[dataset], _sample_factory[task]):
    pass
  return Dataset
```
Messy, but it works.

_Originally posted by @TomsonBoylett in https://github.com/xingyizhou/CenterNet/issues/126#issuecomment-548122873_

**Comment by Libaishun** [comment]
@Ceeeeeeeeeeeeeeb,  Hi, I have the same problem on windows, and I did as you suggested, but it didn't work, the same error still occur when set num_workers > 0; Setting num_workers=0 can skip this error, however slow down the training process very much, I hope there is a real solution to settle this problem

**Comment by wusonglin-ali** [comment]
I got this error
Traceback (most recent call last):
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self.data_queue.get(timeout=timeout)
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 5856) is killed by signal: Floating point exception. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/data/CenterNet-master/src/lib/trains/base_trainer.py", line 125, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/data/CenterNet-master/src/lib/trains/base_trainer.py", line 62, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _get_data
    success, data = self._try_get_data()
  File "/home/wusonglin.wsl/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 5856) exited unexpectedly
