### ISSUE TITLE
Coco dataset path, shape NoneType Error

### ISSUE THREAD

**Issue by omeralierdemir** [xingyizhou/CenterNet#603]
Hi everyone,

`
python main.py ctdet --exp_id coco_dla --batch_size 32 --master_batch 15 --lr 1.25e-4  --gpus 0
Fix size testing.
training chunk_sizes: [15]
The output will be saved to  /home/yz-yki-2/CenterNet/src/lib/../../exp/ctdet/coco_dla
heads {'hm': 80, 'wh': 2, 'reg': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='dla_34', aug_ddd=0.5, aug_rot=0, batch_size=32, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[15], data_dir='/home/yz-yki-2/CenterNet/src/lib/../../data', dataset='coco', debug=0, debug_dir='/home/yz-yki-2/CenterNet/src/lib/../../exp/ctdet/coco_dla/debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='/home/yz-yki-2/CenterNet/src/lib/../../exp/ctdet', exp_id='coco_dla', fix_res=True, flip=0.5, flip_test=False, gpus=[0], gpus_str='0', head_conv=256, heads={'hm': 80, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=512, input_res=512, input_w=512, keep_res=False, kitti_split='3dop', load_model='', lr=0.000125, lr_step=[90, 120], master_batch_size=15, mean=array([[[0.40789655, 0.44719303, 0.47026116]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=80, num_epochs=140, num_iters=-1, num_stacks=1, num_workers=4, off_weight=1, output_h=128, output_res=128, output_w=128, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='/home/yz-yki-2/CenterNet/src/lib/../..', rot_weight=1, rotate=0, save_all=False, save_dir='/home/yz-yki-2/CenterNet/src/lib/../../exp/ctdet/coco_dla', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.2886383 , 0.27408165, 0.27809834]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=5, vis_thresh=0.3, wh_weight=0.1)
Creating model...
Setting up data...
==> initializing coco 2017 val data.
annotationssss pathhhhhh  /home/yz-yki-2/CenterNet/src/lib/../../data/coco/annotations/instances_val2014.json
loading annotations into memory...
Done (t=0.28s)
creating index...
index created!
Loaded val 5000 samples
==> initializing coco 2017 train data.
annotationssss pathhhhhh  /home/yz-yki-2/CenterNet/src/lib/../../data/coco/annotations/instances_train2014.json
loading annotations into memory...
Done (t=8.32s)
creating index...
index created!
Loaded train 118287 samples
Starting training...
ctdet/coco_dla/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_val2014_000000022819.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_val2014_000000145015.jpg imagee pattthhhh
Traceback (most recent call last):
  File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/yz-yki-2/CenterNet/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/yz-yki-2/CenterNet/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/yz-yki-2/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/yz-yki-2/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/home/yz-yki-2/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yz-yki-2/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/yz-yki-2/CenterNet/src/lib/datasets/sample/ctdet.py", line 40, in __getitem__
    height, width = img.shape[0], img.shape[1]
AttributeError: 'NoneType' object has no attribute 'shape'

/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000443315.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000526441.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000305141.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000004318.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_val2014_000000408818.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_val2014_000000464153.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000401699.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000328228.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000142229.jpg imagee pattthhhh
/home/yz-yki-2/CenterNet/src/lib/../../data/coco/train2014/COCO_train2014_000000149915.jpg imagee pattthhhh
`

I get this error. I want to train model with coco2014 dataset. For this I have customized coco.py. I think my annatosion and data(train,val,test) directories path is wrong path. Where is annotation directory and data directory path-location ?

**Comment by Veronica1997** [comment]
I meet the same problem with you , Have you solved it ? Thanks!

**Comment by AnnetGeorge** [comment]
I was getting this error when using my custom dataset and the issue was related to my folder structure. The folder structure the code expects can be found by printing the image path in code. For example in my case, I was using ctdet so in the ctdet.py file (in the samples folder) I printed img_path (print(img_path)) after this line:
img = cv2.imread(img_path)

That showed that my images need to be in a folder named JPEGImages (like in the COCO dataset).
