### ISSUE TITLE
I need help.I meet a ERROR:OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by QingshuiL** [xingyizhou/CenterNet#613]
I train the HourGlass on my datasets.When I load the model and test it on my test data,I meet a OSError.
`Creating model...
Traceback (most recent call last):
  File "test.py", line 124, in <module>
    test(opt)
  File "test.py", line 93, in test
    detector = Detector(opt)
  File "C:\Users\10295\CV\CenterNet-master\src\lib\detectors\ctdet.py", line 26, in __init__
    super(CtdetDetector, self).__init__(opt)
  File "C:\Users\10295\CV\CenterNet-master\src\lib\detectors\base_detector.py", line 25, in __init__
    self.model = load_model(self.model, opt.load_model)
  File "C:\Users\10295\CV\CenterNet-master\src\lib\models\model.py", line 34, in load_model
    checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "D:\Program Files (x86)\Anconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\Program Files (x86)\Anconda3\envs\pytorch\lib\site-packages\torch\serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
OSError: [Errno 22] Invalid argument`

**Comment by QingshuiL** [comment]
![(@F$XA1WHC@3690PU(ICP0Z](https://user-images.githubusercontent.com/37494187/74463382-ba0e0f80-4ecc-11ea-8355-ae9d5d2d8f3d.png)
