### ISSUE TITLE
Training not OOM, but demo.py OOM

### ISSUE THREAD

**Issue by qingzhouzhen** [xingyizhou/CenterNet#640]
run inference(demo.py) Out Of Memory(OOM)
### environment
ubuntu16.4
torch0.41
cuda9.2
GPU: RTX2070(8G)
### question
I folowed https://github.com/xingyizhou/CenterNet/tree/master/experiments 
use script `python main.py ctdet --exp_id coco_dla_1x --batch_size 8 --master_batch 8 --lr 5e-4 --gpus 0 ` and training is OK
but inference got OOM error
use script `python demo.py ctdet --demo /data/project/CenterNet/images --load_model /data/project/CenterNet/exp/ctdet/coco_dla_1x/model_best.pth`
 
it complains:
```
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /data/project/CenterNetOrigin/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded /data/project/CenterNetOrigin/CenterNet/exp/ctdet/coco_dla_1x/model_best.pth, epoch 25
Traceback (most recent call last):
  File "/data/project/CenterNetOrigin/CenterNet/src/demo.py", line 56, in <module>
    demo(opt)
  File "/data/project/CenterNetOrigin/CenterNet/src/demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/data/project/CenterNetOrigin/CenterNet/src/lib/detectors/base_detector.py", line 116, in run
    output, dets, forward_time = self.process(images, return_time=True)
  File "/data/project/CenterNetOrigin/CenterNet/src/lib/detectors/ctdet.py", line 30, in process
    output = self.model(images)[-1]
  File "/data/softinstall/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/project/CenterNetOrigin/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 481, in forward
    z[head] = self.__getattr__(head)(y[-1])
  File "/data/softinstall/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/softinstall/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/data/softinstall/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/softinstall/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

Process finished with exit code 1
```

### My analysis
I found OOM happend in `pose_dla_dcn.py`:
```
    def forward(self, x):
        x = self.base(x)
        x = self.dla_up(x)

        y = []
        for i in range(self.last_level - self.first_level):
            y.append(x[i].clone())
        self.ida_up(y, 0, len(y))

        z = {}
        for head in self.heads:
            # oom here
            z[head] = self.__getattr__(head)(y[-1])
        return [z]
``` 
just the feature to generate first heatmap hm.

inputs of training is 8 example, and one for inference, why inference got OOM?

**Comment by xingyizhou** [comment]
I heard there are some inconsistencies between RTX and torch0.4. Please try torch 1.0+(and replace the DCNv2 branch) to see if the problem still exists.

**Comment by xingyizhou** [comment]
Closing this for now. Feel free to reopen if you have further questions.
