### ISSUE TITLE
undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

### ISSUE THREAD

**Issue by HuangDihe** [xingyizhou/CenterNet#646]
env: ubuntu cuda10.0 torch1.1.0 torchvision0.3.0 python3.6 
I finished all the installation successfully. But when I run the demo `python demo.py ctdet --demo /home/ljh/workspace/CenterNet-master/images --load_model /home/ljh/workspace/CenterNet-master/models/ctdet_coco_dla_2x.pth`
I get this error
`
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/ljh/workspace/CenterNet-master/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/ljh/workspace/CenterNet-master/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/home/ljh/workspace/CenterNet-master/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/ljh/workspace/CenterNet-master/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/ljh/workspace/CenterNet-master/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/ljh/workspace/CenterNet-master/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /home/ljh/workspace/CenterNet-master/src/lib/models/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

**Comment by HuangDihe** [comment]
I remove the conda env, create a new conda env and do the same thing again, then problem finished.[http://www.luyixian.cn/news_show_75656.aspx](url)
error：
undefined symbol: _ZN3c105ErrorC1 ENS_14SourceLocationERKSs 
reson：in pytoch, _GLIBCXX_USE_CXX11_ABI is 1，but c++ complies _GLIBCXX_USE_CXX11_ABI to 0，which causes this problem.
实际原因是pytorch编译时候用到的gcc与代码中c++库用到的gcc版本不同
解决方法：
卸载conda，重新安装conda，此时conda环境用到的gcc与c++编译库时版本一样。

**Comment by 916968505** [comment]
@HuangDihe 请问要安装什么版本的g++和gcc？
