### ISSUE TITLE
After training,run demo.py to half met a problem

### ISSUE THREAD

**Issue by pikapikazhou** [xingyizhou/CenterNet#658]
Hi, I trained CenterNet on my own dataset of 117 labels . And didn‘t appear any error in the training and testing process . When I run demo.py to half , I met a problem as follows.The strange thing is that in the test image output by the demo before the error was reported, all the labels are correct, not the 80 types of labels in the coco dataset.I would like to ask you what went wrong, and hope to get your reply

tot 0.075s |load 0.035s |pre 0.016s |net 0.019s |dec 0.001s |post 0.004s |merge 0.001s |
tot 0.085s |load 0.047s |pre 0.013s |net 0.020s |dec 0.001s |post 0.004s |merge 0.001s |
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 49, in demo
    ret = detector.run(image_name)
  File "/home1/huangqian/zmq/food_detection/CenterNet/CenterNet-master/src/lib/detectors/base_detector.py", line 140, in run
    self.show_results(debugger, image, results)
  File "/home1/huangqian/zmq/food_detection/CenterNet/CenterNet-master/src/lib/detectors/ctdet.py", line 95, in show_results
    debugger.add_coco_bbox(bbox[:4], j - 1, bbox[4], img_id='ctdet')
  File "/home1/huangqian/zmq/food_detection/CenterNet/CenterNet-master/src/lib/utils/debugger.py", line 178, in add_coco_bbox
    c = self.colors[cat][0][0].tolist()
IndexError: index 105 is out of bounds for axis 0 with size 80

**Comment by blacklong617** [comment]
The color_list  in debugger.py size is 80 , is not enough for you.

**Comment by JoeyHang** [comment]
Hi, I met the exact same question when running demo.py on my own dataset, can you tell me how you solve this problem? Thanks a lot!

**Comment by JoeyHang** [comment]
> The color_list in debugger.py size is 80 , is not enough for you.

hi, can you tell me how to change the color_list? Thanks a lot!

**Comment by pikapikazhou** [comment]
> The color_list in debugger.py size is 80 , is not enough for you.

thanks a lot . I found the problem too

**Comment by pikapikazhou** [comment]
> > The color_list in debugger.py size is 80 , is not enough for you.
> 
> hi, can you tell me how to change the color_list? Thanks a lot!

just add more  in color list to fit your categories
