### ISSUE TITLE
indexerror

### ISSUE THREAD

**Issue by czy112** [xingyizhou/CenterNet#682]

**Comment by czy112** [comment]
Loaded train 3825 samples
Starting training...
ctdet/headfile_name:1400521.jpg
E:\CenterNet\src\lib....\data\hand\images\1400521.jpg
20190000268
Traceback (most recent call last):
File "main.py", line 102, in
main(opt)
File "main.py", line 70, in main
log_dict_train, _ = trainer.train(epoch, train_loader)
File "E:\CenterNet\src\lib\trains\base_trainer.py", line 119, in train
return self.run_epoch('train', epoch, data_loader)
File "E:\CenterNet\src\lib\trains\base_trainer.py", line 61, in run_epoch
for iter_id, batch in enumerate(data_loader):
File "F:\ana\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in next
batch = self.collate_fn([self.dataset[i] for i in indices])
File "F:\ana\envs\torch\lib\site-packages\torch\utils\data\dataloader.py", line 560, in
batch = self.collate_fn([self.dataset[i] for i in indices])
File "E:\CenterNet\src\lib\datasets\sample\ctdet.py", line 126, in getitem
draw_gaussian(hm[cls_id], ct_int, radius)
IndexError: index 1 is out of bounds for axis 0 with size 1

how to solove this?
plsease
win10+cuda10+torch1.1

**Comment by xingyizhou** [comment]
You need to manually match the `category_id` field in COCO annotation format (usually starts from 1) to a 0-based continuous index. Check the `_valid_ids` valuable in the dataset definition file.

**Comment by Juphex** [comment]
> You need to manually match the `category_id` field in COCO annotation format (usually starts from 1) to a 0-based continuous index. Check the `_valid_ids` valuable in the dataset definition file.

You could also modify `self._valid_ids ` so  it starts it 0, right? Should not matter, right? :)
