### ISSUE TITLE
Runtime error running demo.py

### ISSUE THREAD

**Issue by MZHI** [xingyizhou/CenterNet#722]
Hi, I install CenterNet and trying to run demo.py:
`python demo.py ctdet --demo /path/to/image/or/folder/or/video --load_model ../models/ctdet_coco_dla_2x.pth`

and get RuntimeError:
`Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/gecktor/proj_src/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
Traceback (most recent call last):
  File "demo.py", line 56, in <module>
    demo(opt)
  File "demo.py", line 21, in demo
    detector = Detector(opt)
  File "/home/gecktor/proj_src/CenterNet/src/lib/detectors/ctdet.py", line 26, in __init__
    super(CtdetDetector, self).__init__(opt)
  File "/home/gecktor/proj_src/CenterNet/src/lib/detectors/base_detector.py", line 24, in __init__
    self.model = create_model(opt.arch, opt.heads, opt.head_conv)
  File "/home/gecktor/proj_src/CenterNet/src/lib/models/model.py", line 28, in create_model
    model = get_model(num_layers=num_layers, heads=heads, head_conv=head_conv)
  File "/home/gecktor/proj_src/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 491, in get_pose_net
    head_conv=head_conv)
  File "/home/gecktor/proj_src/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 434, in __init__
    self.base = globals()[base_name](pretrained=pretrained)
  File "/home/gecktor/proj_src/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 314, in dla34
    model.load_pretrained_model(data='imagenet', name='dla34', hash='ba72cf86')
  File "/home/gecktor/proj_src/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 300, in load_pretrained_model
    model_weights = model_zoo.load_url(model_url)
  File "/home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/hub.py", line 506, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 2109139 more bytes. The file might be corrupted.
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at /pytorch/c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at /pytorch/c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2a542f8193 in /home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x18697ef (0x7f2a55d877ef in /home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #2: THStorage_free + 0x17 (0x7f2a5654fdf7 in /home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x55cb5d (0x7f2aa9c8db5d in /home/gecktor/environments/env_torch_pg/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: python() [0x536b4c]
frame #5: python() [0x517497]
frame #6: python() [0x5e6118]
frame #7: python() [0x4fa2a7]
frame #8: python() [0x4dcf27]
frame #9: python() [0x4dcf3d]
frame #10: python() [0x4dcf3d]
frame #11: python() [0x4dcf3d]
frame #12: python() [0x4dcf3d]
frame #13: python() [0x4dcf3d]
frame #14: python() [0x4dcf3d]
frame #15: python() [0x4dcf3d]
frame #16: python() [0x4dcf3d]
frame #17: python() [0x4dcf3d]
frame #18: python() [0x4dcf3d]
frame #19: python() [0x4dcf3d]
frame #20: python() [0x601e5a]
<omitting python frames>
frame #26: __libc_start_main + 0xf0 (0x7f2ab6fa1830 in /lib/x86_64-linux-gnu/libc.so.6)

Aborted (core dumped)`

My environment:
ubuntu 16.04
python 3.6.10
cuda 9.2
pytorch version: 1.4.0+cu92
torchvision version: 0.5.0+cu92

**Comment by woaichipinngguo** [comment]
try pretrained = False ?

![image](https://user-images.githubusercontent.com/15664013/83318336-7adeb100-a266-11ea-8afb-f457a92d9287.png)

**Comment by MZHI** [comment]
> try pretrained = False ?
> 
> ![image](https://user-images.githubusercontent.com/15664013/83318336-7adeb100-a266-11ea-8afb-f457a92d9287.png)

Thank you! This solved my issue!
