### ISSUE TITLE
undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE when run the demo

### ISSUE THREAD

**Issue by 916968505** [xingyizhou/CenterNet#735]
Cuda 10.1
Pytorch 1.0.1

I followed this [https://github.com/xingyizhou/CenterNet/issues/7](url) issue to compile my Dcnv2
but when I run the demo by use
`python demo.py ctdet --demo ~/CenterNet/images/18124840932_e42b3e377c_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth
`
I got an erorr 
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/home/caojinghao/CenterNet/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/home/caojinghao/CenterNet/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/home/caojinghao/CenterNet/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/home/caojinghao/CenterNet/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/home/caojinghao/CenterNet/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/home/caojinghao/CenterNet/src/lib/models/networks/DCNv2/dcn_v2.py", line 13, in <module>
    import _ext as _backend
ImportError: /home/caojinghao/CenterNet/src/lib/models/networks/DCNv2/_ext.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c1019UndefinedTensorImpl10_singletonE

I have try to reinstall my gcc and conda ,but didn't work.
who knows why?

**Comment by 916968505** [comment]
I tried to solve this problem as this way  [https://github.com/xingyizhou/CenterNet/issues/646](url)
but is also didn't work well

**Comment by alexrider1105** [comment]
I also encountered this issue using CUDA 10.1 and pytorch 1.0.0
