### ISSUE TITLE
KeyError: 12 when training

### ISSUE THREAD

**Issue by yao-zheng-yi** [xingyizhou/CenterNet#754]
anyone can help me？

ctdet/yxh |###                             | train: [1][1152/11176]|Tot: 0:03:32 |ETA: 0:31:52 |loss 7.0469 |hm_loss 5.6721 |wh_loss 11.1695 |off_loss 0.2578 |Dat
ctdet/yxh |###                             | train: [1][1153/11176]|Tot: 0:03:32 |ETA: 0:31:52 |loss 7.0438 |hm_loss 5.6696 |wh_loss 11.1645 |off_loss 0.2578 |Dat
ctdet/yxh |###                             | train: [1][1154/11176]|Tot: 0:03:33 |ETA: 0:31:52 |loss 7.0415 |hm_loss 5.6676 |wh_loss 11.1610 |off_loss 0.2578 |Dat
ctdet/yxh |###                             | train: [1][1155/11176]|Tot: 0:03:33 |ETA: 0:31:52 |loss 7.0397 |hm_loss 5.6666 |wh_loss 11.1537 |off_loss 0.2578 |Dat
ctdet/yxh |###                             | train: [1][1156/11176]|Tot: 0:03:33 |ETA: 0:28:37 |loss 7.0365 |hm_loss 5.6640 |wh_loss 11.1480 |off_loss 0.2578 |Dat
ctdet/yxh |###                             | train: [1][1157/11176]|Tot: 0:03:33 |ETA: 0:28:37 |loss 7.0330 |hm_loss 5.6611 |wh_loss 11.1411 |off_loss 0.2578 |Data 0.002s(0.002s) |Net 0.185sTraceback (most recent call last):
File "main.py", line 102, in <module>
    main(opt)
  File "main.py", line 70, in main
    log_dict_train, _ = trainer.train(epoch, train_loader)
  File "/home/cwy/CenterNet-master/src/lib/trains/base_trainer.py", line 119, in train
    return self.run_epoch('train', epoch, data_loader)
  File "/home/cwy/CenterNet-master/src/lib/trains/base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "/home/cwy/.conda/envs/yolo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 568, in __next__
    return self._process_next_batch(batch)
  File "/home/cwy/.conda/envs/yolo/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 606, in _process_next_batch
    raise Exception("KeyError:" + batch.exc_msg)
Exception: KeyError:Traceback (most recent call last):
  File "/home/cwy/.conda/envs/yolo/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cwy/.conda/envs/yolo/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/cwy/CenterNet-master/src/lib/datasets/sample/ctdet.py", line 102, in __getitem__
    cls_id = int(self.cat_ids[ann['category_id']])
KeyError: 12

**Comment by yao-zheng-yi** [comment]
I guess the problem maybe in train.json，but I can‘t find error.
感觉是json文件的问题，但是有时候又可以正常训练，报错信息太少了不知道怎么找原因，到底是哪里出错了呢？

**Comment by yao-zheng-yi** [comment]
我知道了，类别ID的列表少了个12，低级错误

**Comment by wwq98** [comment]
你好 请问怎么解决呢？

**Comment by wwq98** [comment]
解决了
