### ISSUE TITLE
Building original DCNv2 runtime error

### ISSUE THREAD

**Issue by nnuk** [xingyizhou/CenterNet#766]
While building the original DCNv2 I get the folllowing error. I am working with this though :
Cuda -> 10.1
cudnn -> 7.0
PyTorch -> 1.5.1
Visual Studio Code -> 1.46.1
Python 3.7
OS Windows 10.

-----error-----

PS D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2> python setup.py build develop
running build
running build_ext
C:\Users\nauma\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:238: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building '_ext' extension
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src 
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu
creating D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cuda
Emitting ninja build file D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/7] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\vision.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\vision.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/build/temp.win-amd64-3.7/Release/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/src/vision.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\vision.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\vision.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[2/7] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_psroi_pooling_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_psroi_pooling_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/build/temp.win-amd64-3.7/Release/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_psroi_pooling_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_psroi_pooling_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_psroi_pooling_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[3/7] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/build/temp.win-amd64-3.7/Release/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
[4/7] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_im2col_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_im2col_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
FAILED: D:/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/build/temp.win-amd64-3.7/Release/Master Project/MasterProjectTask/CenterNet/src/lib/models/networks/DCNv2/src/cpu/dcn_v2_im2col_cpu.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /EHsc -DWITH_CUDA "-ID:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src" -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\nauma\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include" -IC:\Users\nauma\anaconda3\include -IC:\Users\nauma\anaconda3\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" -c "D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_im2col_cpu.cpp" /Fo"D:\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\build\temp.win-amd64-3.7\Release\Master Project\MasterProjectTask\CenterNet\src\lib\models\networks\DCNv2\src\cpu\dcn_v2_im2col_cpu.obj" -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 /std:c++14
CreateProcess failed: The system cannot find the file specified.
ninja: fatal: ReadFile: The handle is invalid.

Traceback (most recent call last):
  File "C:\Users\nauma\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "C:\Users\nauma\anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "C:\Users\nauma\anaconda3\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\nauma\anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\nauma\anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\nauma\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\nauma\anaconda3\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\nauma\anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Users\nauma\anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\nauma\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 87, in run
    _build_ext.run(self)
  File "C:\Users\nauma\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\nauma\anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "C:\Users\nauma\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 603, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\nauma\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "C:\Users\nauma\anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "C:\Users\nauma\anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    depends=ext.depends)
    with_cuda=with_cuda)
  File "C:\Users\nauma\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1163, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "C:\Users\nauma\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

**Comment by liuxingbin** [comment]
have you solve the problem?

**Comment by shairoz-deci** [comment]
@nnuk have you resolved the issue?

**Comment by Passenger12138** [comment]
I'm also get this problem,so have you resolved the problems?

**Comment by fabrizioschiano** [comment]
I have the same problem. did you solve it?

**Comment by Fansgithub2019** [comment]
have you solve the problem?
