### ISSUE TITLE
AttributeError: Can't pickle local object 'get_dataset.<locals>.Dataset'   和  PermissionError: [WinError 5] 拒绝访问。大佬们这两个问应该怎么解决

### ISSUE THREAD

**Issue by ZHANG-hengzhi** [xingyizhou/CenterNet#860]
D:\anaconda\envs\pytorch\python.exe D:/pycharm/code/CenterNet-master/src/main.py
Fix size testing.
training chunk_sizes: [4]
The output will be saved to  D:\pycharm\code\CenterNet-master\src\lib\..\..\exp\ctdet\mask
heads {'hm': 2, 'wh': 2, 'reg': 2}
Namespace(K=100, aggr_weight=0.0, agnostic_ex=False, arch='dla_34', aug_ddd=0.5, aug_rot=0, batch_size=4, cat_spec_wh=False, center_thresh=0.1, chunk_sizes=[4], data_dir='D:\\pycharm\\code\\CenterNet-master\\src\\lib\\..\\..\\data', dataset='mask', debug=0, debug_dir='D:\\pycharm\\code\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet\\mask\\debug', debugger_theme='white', demo='', dense_hp=False, dense_wh=False, dep_weight=1, dim_weight=1, down_ratio=4, eval_oracle_dep=False, eval_oracle_hm=False, eval_oracle_hmhp=False, eval_oracle_hp_offset=False, eval_oracle_kps=False, eval_oracle_offset=False, eval_oracle_wh=False, exp_dir='D:\\pycharm\\code\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet', exp_id='mask', fix_res=True, flip=0.5, flip_test=False, gpus=[0], gpus_str='0', head_conv=256, heads={'hm': 2, 'wh': 2, 'reg': 2}, hide_data_time=False, hm_hp=True, hm_hp_weight=1, hm_weight=1, hp_weight=1, input_h=512, input_res=512, input_w=256, keep_res=False, kitti_split='3dop', load_model='', lr=0.000125, lr_step=[90, 120], master_batch_size=4, mean=array([[[0.5372384 , 0.5420533 , 0.55804765]]], dtype=float32), metric='loss', mse_loss=False, nms=False, no_color_aug=False, norm_wh=False, not_cuda_benchmark=False, not_hm_hp=False, not_prefetch_test=False, not_rand_crop=False, not_reg_bbox=False, not_reg_hp_offset=False, not_reg_offset=False, num_classes=2, num_epochs=5, num_iters=-1, num_stacks=1, num_workers=0, off_weight=1, output_h=128, output_res=128, output_w=64, pad=31, peak_thresh=0.2, print_iter=0, rect_mask=False, reg_bbox=True, reg_hp_offset=True, reg_loss='l1', reg_offset=True, resume=False, root_dir='D:\\pycharm\\code\\CenterNet-master\\src\\lib\\..\\..', rot_weight=1, rotate=0, save_all=False, save_dir='D:\\pycharm\\code\\CenterNet-master\\src\\lib\\..\\..\\exp\\ctdet\\mask', scale=0.4, scores_thresh=0.1, seed=317, shift=0.1, std=array([[[0.23800112, 0.24400982, 0.2351255 ]]], dtype=float32), task='ctdet', test=False, test_scales=[1.0], trainval=False, val_intervals=2, vis_thresh=0.3, wh_weight=0.1)
Creating model...
'cp' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���
Setting up data...
==> initializing mask val data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded val 3 samples
==> initializing mask train data.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Loaded train 6 samples
Starting training...
D:\anaconda\envs\pytorch\lib\site-packages\torch\nn\_reduction.py:46: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
Traceback (most recent call last):
  File "D:/pycharm/code/CenterNet-master/src/main.py", line 102, in <module>
    main(opt)
  File "D:/pycharm/code/CenterNet-master/src/main.py", line 79, in main
    log_dict_val, preds = trainer.val(epoch, val_loader)
  File "D:\pycharm\code\CenterNet-master\src\lib\trains\base_trainer.py", line 116, in val
    return self.run_epoch('val', epoch, data_loader)
  File "D:\pycharm\code\CenterNet-master\src\lib\trains\base_trainer.py", line 61, in run_epoch
    for iter_id, batch in enumerate(data_loader):
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 193, in __iter__
    return _DataLoaderIter(self)
  File "D:\anaconda\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 469, in __init__
    w.start()
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_dataset.<locals>.Dataset'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "D:\anaconda\envs\pytorch\lib\multiprocessing\reduction.py", line 87, in steal_handle
    _winapi.DUPLICATE_SAME_ACCESS | _winapi.DUPLICATE_CLOSE_SOURCE)
PermissionError: [WinError 5] 拒绝访问。

**Comment by zzh48** [comment]
I meet this problem too, do you find out solution?

**Comment by Hd-14** [comment]
I meet the same problem, do you solve this problem?

**Comment by Dovahkiin2233** [comment]
make sure all num_workers = 0

**Comment by xuzekai1997** [comment]
> make sure all num_workers = 0

hello,I set num_workers=0,But it still raise the same problem.
