### ISSUE TITLE
Trying to build CenterNet on pytorch1.6, fail to build DCN

### ISSUE THREAD

**Issue by shairoz-deci** [xingyizhou/CenterNet#861]
I am trying to run CenterNet on pytorch 1.6, I followed the steps on
https://github.com/xingyizhou/CenterNet/issues/7
 and I'm failing on the second stage, building the DCNv2 from the original repo.

`python setup.py build develop`

outputs:
Traceback (most recent call last):
  File "setup.py", line 70, in <module>
    cmdclass={"build_ext": torch.utils.cpp_extension.BuildExtension},
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 649, in build_extensions
    build_ext.build_extensions(self)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 205, in build_extension
    _build_ext.build_extension(self, ext)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 478, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1233, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/apps/conda/anaconda/envs/deci-development/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1529, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error compiling objects for extension

Any idea how to overcome and build for pytorch 1.6?
other envs:
torchvision            0.7.0
CUDA 10.2

Thanks in advance

**Comment by rootonchair** [comment]
@shairoz-deci Yes, the one in this repo is broken. You should clone from the [original DCN](https://github.com/CharlesShang/DCNv2) and install it instead

Please reference [this Colab Notebook](https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/CenterNet_ObjectsAsPoints.ipynb)

**Comment by shairoz-deci** [comment]
@rootonchair Thank you for your reply, I did use the original DCN and I 0 getting the above error on running ./make.sh

**Comment by ChristofHenkel** [comment]
For me it worked to clone a branch specific to your torch version e.g. 

https://github.com/lbin/DCNv2/tree/pytorch_1.7
