### ISSUE TITLE
RuntimeError: Not compiled with GPU support 

### ISSUE THREAD

**Issue by Rogerget21** [xingyizhou/CenterNet#886]
Win10+python3.6.12+pytorch1.1.0+cuda10.0

when I run the demo.py:

(CenterNet) D:\CenterNet\src>python demo.py ctdet --demo ../images/16004479832_a748d55f21_k.jpg --load_model ../models/ctdet_coco_dla_2x.pth
Fix size testing.
training chunk_sizes: [32]
The output will be saved to D:\CenterNet\src\lib....\exp\ctdet\default
heads {'hm': 80, 'wh': 2, 'reg': 2}
Creating model...
loaded ../models/ctdet_coco_dla_2x.pth, epoch 230
Drop parameter base.fc.weight.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Drop parameter base.fc.bias.If you see this, your model does not fully load the pre-trained weight. Please make sure you have correctly specified --arch xxx or set the correct --num_classes for your own dataset.
Traceback (most recent call last):
File "demo.py", line 56, in
demo(opt)
File "demo.py", line 49, in demo
ret = detector.run(image_name)
File "D:\CenterNet\src\lib\detectors\base_detector.py", line 116, in run
output, dets, forward_time = self.process(images, return_time=True)
File "D:\CenterNet\src\lib\detectors\ctdet.py", line 30, in process
output = self.model(images)[-1]
File "D:\ProgramData\anaconda3\envs\CenterNet\lib\site-packages\torch\nn\modules\module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "D:\CenterNet\src\lib\models\networks\pose_dla_dcn.py", line 472, in forward
x = self.dla_up(x)
File "D:\ProgramData\anaconda3\envs\CenterNet\lib\site-packages\torch\nn\modules\module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "D:\CenterNet\src\lib\models\networks\pose_dla_dcn.py", line 411, in forward
ida(layers, len(layers) -i - 2, len(layers))
File "D:\ProgramData\anaconda3\envs\CenterNet\lib\site-packages\torch\nn\modules\module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "D:\CenterNet\src\lib\models\networks\pose_dla_dcn.py", line 384, in forward
layers[i] = upsample(project(layers[i]))
File "D:\ProgramData\anaconda3\envs\CenterNet\lib\site-packages\torch\nn\modules\module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "D:\CenterNet\src\lib\models\networks\pose_dla_dcn.py", line 355, in forward
x = self.conv(x)
File "D:\ProgramData\anaconda3\envs\CenterNet\lib\site-packages\torch\nn\modules\module.py", line 493, in call
result = self.forward(*input, **kwargs)
File "D:\CenterNet\src\lib\models\networks\DCNv2\dcn_v2.py", line 128, in forward
self.deformable_groups)
File "D:\CenterNet\src\lib\models\networks\DCNv2\dcn_v2.py", line 31, in forward
ctx.deformable_groups)
RuntimeError: Not compiled with GPU support (dcn_v2_forward at d:\centernet\src\lib\models\networks\dcnv2\src\dcn_v2.h:35)
(no backtrace available)

Can you please help me with this problem?

**Comment by Rogerget21** [comment]
I followed this article: https://blog.csdn.net/qq_37802410/article/details/105276801

**Comment by Rogerget21** [comment]
I followed this article: https://blog.csdn.net/qq_37802410/article/details/105276801. But when I run demo.py: RuntimeError: Not compiled with GPU support.

**Comment by FangShiYi** [comment]
I have the same problem.Have you solved this problem?
