### ISSUE TITLE
error when I run demo.py

### ISSUE THREAD

**Issue by xdnjust** [xingyizhou/CenterNet#915]
(FR1) [root@localhost src]# python demo.py ctdet --demo ../images --load_model ../models/ctdet_coco_dla_2x.pth

Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from detectors.detector_factory import detector_factory
  File "/users_4/d00477216/4_CenterNet-master/src/lib/detectors/detector_factory.py", line 5, in <module>
    from .exdet import ExdetDetector
  File "/users_4/d00477216/4_CenterNet-master/src/lib/detectors/exdet.py", line 21, in <module>
    from .base_detector import BaseDetector
  File "/users_4/d00477216/4_CenterNet-master/src/lib/detectors/base_detector.py", line 11, in <module>
    from models.model import create_model, load_model
  File "/users_4/d00477216/4_CenterNet-master/src/lib/models/model.py", line 12, in <module>
    from .networks.pose_dla_dcn import get_pose_net as get_dla_dcn
  File "/users_4/d00477216/4_CenterNet-master/src/lib/models/networks/pose_dla_dcn.py", line 16, in <module>
    from .DCNv2.dcn_v2 import DCN
  File "/users_4/d00477216/4_CenterNet-master/src/lib/models/networks/DCNv2/dcn_v2.py", line 11, in <module>
    from .dcn_v2_func import DCNv2Function
  File "/users_4/d00477216/4_CenterNet-master/src/lib/models/networks/DCNv2/dcn_v2_func.py", line 9, in <module>
    from ._ext import dcn_v2 as _backend
ModuleNotFoundError: No module named 'models.networks.DCNv2._ext'

**Comment by Ambuj31** [comment]
Did you find something??? Facing the same issues!

**Comment by howdidthatwork** [comment]
Same, not sure how to fix this

**Comment by sevenandseven** [comment]
I have the same question,can you tell me how to solve?

**Comment by XhHello** [comment]
Need to compile DCNv2.
cd src\lib\models\networks\DCNv2
python setup.py build develop
