### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by almpantoja** [xingyizhou/CenterNet#918]
<module 'sys' (built-in)>
Fix size testing.
training chunk_sizes: [32]
The output will be saved to  /home/Students/amp393/CenterNetDeepSort/env/centerNet-deep-sort/CenterNet/src/lib/../../exp/ctdet/default
heads {'hm': 80, 'wh': 2, 'reg': 2}
/home/Students/amp393/CenterNetDeepSort/env/OverheadActivity/Tracking/Util/Videos/images/
Creating model...
loaded /home/Students/amp393/CenterNetDeepSort/env/OverheadActivity/Tracking/Util/aiskyeye/model_best.pth, epoch 5
Traceback (most recent call last):
  File "centernet_deepsort2_OG.py", line 36, in <module>
    ret = detector.run(img)
  File "/home/Students/amp393/CenterNetDeepSort/env/centerNet-deep-sort/CenterNet/src/lib/detectors/base_detector.py", line 106, in run
    images, meta = self.pre_process(image, scale, meta)
  File "/home/Students/amp393/CenterNetDeepSort/env/centerNet-deep-sort/CenterNet/src/lib/detectors/base_detector.py", line 38, in pre_process
    height, width = image.shape[0:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by almpantoja** [comment]
Having trouble with it trying to read the video. Not really sure where it's going wrong.

**Comment by sicarioakki** [comment]
Facing the same issue while running test.py with python3 test.py ctdet --exp_id coco_dla --keep_res --load_model ../models/ctdet_coco_dla_2x.pth. Have you solved?

**Comment by almpantoja** [comment]
> Facing the same issue while running test.py with python3 test.py ctdet --exp_id coco_dla --keep_res --load_model ../models/ctdet_coco_dla_2x.pth. Have you solved?

No not yet :(

**Comment by Piyal93** [comment]
`AttributeError: 'NoneType' object has no attribute 'shape' `

I have also faced the same error and I solved it. It's an error from the image path. Check the image path in the JSON file.

**Comment by Fansgithub2019** [comment]
https://github.com/xingyizhou/CenterNet/issues/816#issue-703620592
